### ISSUE TITLE
Coding style: Unwanted whitespace and newline at EOF

### ISSUE THREAD

**Issue by Lokaltog** [jonathangeiger/kohana-jelly#100]
I've noticed that there's a lot of unwanted/trailing whitespace in Jelly, as well as missing newlines at the end of some files. I consider it good practice to remove trailing whitespace from all files before committing them, and trailing whitespace is also removed from all files in Kohana core.

I use an autocmd in vim to remove all trailing whitespace when saving PHP files, and vim also automatically adds a newline at EOF to all text files. This messes up the commits when I change files in Jelly, like [this one](https://github.com/Lokaltog/kohana-jelly/commit/0cbd55bb1e9f6b50a4d8a2f37256ce186db41699). 

I know I can just change my configuration to _not_ remove trailing whitespace, but I'd like to know if there's any reason for keeping whitespace in Jelly. If not, I would suggest that someone does some whitespace cleanup (I'd gladly do it) in all Jelly files. :)

**Comment by banks** [comment]
> I would suggest that someone does some whitespace cleanup (I'd gladly do it)

Be our guest! We have no intentions to add trailing whitespace but I guess since different people with different editors work on the code, it is hard to say who or whose editor configurations are doing some of this stuff.

Congrats on posting issue #100!

**Comment by Lokaltog** [comment]
Thanks! :P

I've cleaned up whitespace in all the files and chmodded classes/jelly/model/core.php to 644 like all the other files: 15c1f6fee414f113aa72309b2babaddcfc3aafbb.

**Comment by banks** [comment]
> chmodded classes/jelly/model/core.php to 644

I wasn't aware that git stored file permissions - if something was funny on your machine it isn't anything to do with the repository. Please correct me if I'm wrong.

**Comment by Lokaltog** [comment]
Yeah, git stores permissions. If you check out my commit you'll see this:

```
classes/jelly/model/core.php 100755 → 100644
```

It was 755 in 28b73ef712aeebcbeb9d2a48368d175011e0acac ([proof](/jonathangeiger/kohana-jelly/blob/master/classes/jelly/model/core.php)). :)

**Comment by banks** [comment]
I stand corrected. Good to know. Thanks. We'll merge this cleanup when one of us gets a chance - I have a crazy couple of weeks coming up and Jon has just had one but hopefully we'll get some more time to work on this code soon...

**Comment by jonathangeiger** [comment]
Closed by 15c1f6fee414f113aa72309b2babaddcfc3aafbb. Thanks alot!
