### ISSUE TITLE
Jelly cache solution

### ISSUE THREAD

**Issue by syrusakbary** [jonathangeiger/kohana-jelly#101]
Hello,
Today I've noticied that I cannot cache the requests like the Database_Query way

> Jelly::select('table')->**cached(10)**->execute();

I have view the source of Jelly, and I found a very simple solution.
Just put in the **_build** method of the **Jelly_Builder_Core** class

> $query->_lifetime     = $this->_lifetime;

So, the source in the _build function will be like this:

> protected function _build($type = NULL)
>   {
>       if ($type === NULL)
>       {
>           $type = $this->_type;
>       }
>       switch($type)
>       {
>           case Database::SELECT:
>               if ($this->_meta AND ! count($this->_order_by))
>               {
>                   // Don't add default sorting if order_by() has been set manually
>                   foreach ($this->_meta->sorting() as $column => $direction)
>                   {
>                       $this->order_by($column, $direction);
>                   }
>                 }
>                 $query = DB::select();
>                 $query->_from       = $this->_from;
>                 $query->_select     = $this->_select;
>                 **$query->_lifetime     = $this->_lifetime;**
>                 $query->_distinct   = $this->_distinct;
>                 $query->_offset     = $this->_offset;
>                 $query->_limit      = $this->_limit;
>                 $query->_join       = $this->_join;
>                 $query->_group_by   = $this->_group_by;
>                 $query->_order_by   = $this->_order_by;
>                 $query->_as_object  = $this->_as_object;
>                 break;
> ....

**Comment by Lokaltog** [comment]
I've noticed this as well. I committed an almost identical change to my fork a couple of days ago: 453cff115f1f6191dc13e6c6216c91943cee5d57

**Comment by jonathangeiger** [comment]
Closed by a00fb4980c399fd4f29352a56bf27a510cb2f85b. Thanks alot for your help SyrusAkbary!
