### ISSUE TITLE
$_having is not transferred in Jelly_Builder::_build()

### ISSUE THREAD

**Issue by ccazette** [jonathangeiger/kohana-jelly#104]
This is resulting in the Jelly builder ignoring having(), and_having() and or_having() clauses.

**Comment by banks** [comment]
Thanks for the report. Hopefully should be fixed as soon as one of us gets a minute.

**Comment by jonathangeiger** [comment]
Closed by fae709764758d08f5587d5f78efd524a4ce8e5e5. Thanks ccazette.
