### ISSUE TITLE
Jelly_Field extending in modules

### ISSUE THREAD

**Issue by smgladkovskiy** [jonathangeiger/kohana-jelly#108]
I build some module which uses Jelly. In my model I want to define some fields to work with. But my extension
    ...
    // MODPATH.modulename/classes/jelly/field.php
    class Jelly_Field extends Jelly_Field_Core {
        // Needs to display field in forms
        public $in_form = TRUE;
    ...
doesn't affect my models. When I put this in APPPATH.classes/jelly/field.php it works like a charm.
Is there some shamanism needed to make it work or I can use Jelly_Field extensions only in APPPATH?

**Comment by jonathangeiger** [comment]
Is your module loaded before or after Jelly? If its after, Jelly's Jelly_Field will be found first and loaded instead of yours.

**Comment by smgladkovskiy** [comment]
Oh, I see. Jelly go first in modules loading. Tomorrow I will try to load my module first.
Thanks and sorry for so dummy issue... :)

**Comment by jonathangeiger** [comment]
Glad to help. :)
