### ISSUE TITLE
Cannot manually specify the primary key on PostgresSQL

### ISSUE THREAD

**Issue by jonathangeiger** [jonathangeiger/kohana-jelly#109]
[This test](http://github.com/jonathangeiger/jelly-tests/blob/master/tests/Jelly/CreateAndUpdate.php#L58) is currently failing on Postgres because I can't get the PostgresSQL driver to return the actual last insert id when it's manually specified:

```
// This works since the id is automatically incremented
$model = Jelly::factory('post');
$model->save();

// This fails
$model = Jelly::factory('post');
$model->id = 9000;
$model->save();
```

My guess is that the driver simply can't return it in the way that MySQL can because of [this line](http://github.com/cbandy/kohana-postgresql/blob/579ad4b8bec54682506aa2157d1c91a7ac71a3f7/classes/kohana/database/postgresql.php#L169). I guest LASTVAL() returns the last auto-incremented ID, but when you manually specify it, nothing is returned. 

If anyone with more experience with Postgres can think about this problem a bit more and help out it would be much appreciated.

A possible solution might be around [this line](http://github.com/jonathangeiger/kohana-jelly/blob/bcc0a185c60f37d59b98a4e2c4ec4daf89c11352/classes/jelly/model/core.php#L477). Perhaps it would be best to simply not override the primary key if a sensible value is not returned (a string or integer). This might be kind of hacky.

**Comment by leth** [comment]
Are these of any help?
http://www.phpriot.com/articles/migrate-from-mysql-to-postgresql/4
http://www.postgresql.org/docs/8.4/interactive/datatype-numeric.html#DATATYPE-SERIAL

**Comment by cbandy** [comment]
OIDs are not typically used on tables with a primary key, and the result of LASTVAL() is affected by triggers. The reliable way to retrieve the identity of an inserted row is to use the [RETURNING](http://www.postgresql.org/docs/current/static/sql-insert.html) syntax of PostgreSQL.

Kohana's database module does not support this API, though a solution has been proposed. See this [issue](http://dev.kohanaframework.org/issues/2188) for the full discussion.

**Comment by jonathangeiger** [comment]
Closing for now, then. Thanks for your help cbandy.
