### ISSUE TITLE
Dynamic Model Methods (Overloading get_by and get_by_related)

### ISSUE THREAD

**Issue by jerfowler** [jonathangeiger/kohana-jelly#110]
I'm about to commit a new feature that will mimic similar ORM features that returns a collection of a model based on a field value of that model or a related model. 

Example:

```
            // Find all open posts
            // 'open' is a char field in the post model
            $posts = Jelly::factory('post')
                    ->get_by_open('Y');

            // Find all posts created by greg
            // 'author' is a BelongsTo field in the post model
            // 'name' is a field of the model to which author references
            $posts = Jelly::factory('post')
                    ->get_by_related_author('name', 'Greg');

            // Shorter way to say that
            // for single string value, :name_key is used
            // for single integer value, :primary_key is used
            $posts = Jelly::factory('post')
                    ->get_by_related_author('Greg');

            // Even shorter way
            // Relationship Fields are passed automatically to the related function
            // Easier to type, the trade-off is slightly more processing overheaded
            $posts = Jelly::factory('post')
                    ->get_by_author('Greg');


            // Find all the users who are not admins
            // 'roles' is a ManyToMany field in user
            // When three parameters are used, the middle is used as the operator
            $users = Jelly::factory('user')
                    ->get_by_related_roles('name', '<>', 'admin');


            // Find all the users who are admins or managers
            // Multiple where clauses can be used by enclosing them in arrays
            // When four parameters are used, the first must be a 'and' or 'or'
            // When three parameters are used, the middle is used as the operator
            $users = Jelly::factory('user')
                    ->get_by_related_roles(array('name', '=', 'admin'), array('or', 'name', '=', 'manager'));
```

I just need to finish testing the code, so I'll commit this feature once I'm done.

**Comment by jerfowler** [comment]
Well, I finished testing, took longer than expected. Had more bugs than I had originally thought. I had to make a change on the syntax when using multiple where statements with and/or. Now you encase it within a 'or' or 'and' indexed array.

```
        $users = Jelly::factory('user')
                ->get_by_related_roles(array('name', '=', 'admin'), 
                          array('or' => array('name', '=', 'manager')));
```

**Comment by jerfowler** [comment]
Just to point out that can be shortened to:
        $users = Jelly::factory('user')
                ->get_by_roles(array('admin'), array('or' => 'manager'))

Since no field value used and we're passing a sting, :name_key is used. 

Which could also be called like this:
        $users = Jelly::factory('user')
                ->get_by_roles(array(':name_key', 'IN', array('admin', 'manager')));

The biggest advantage of using get_by_related is that its all done with a single SQL query.

**Comment by jonathangeiger** [comment]
I think this can be leveraged for #27, but I'm not entirely sure I like the API. We also want to avoid mucking up __call() for now because of #22.

Take a look at [this](http://github.com/jonathangeiger/kohana-jelly/issues#issue/27/comment/154282).

I'll see if we can incorporate this soon.

**Comment by dewos** [comment]
In my opinion, this auto-api-like-stuff should really be optional and not in the official API, but maybe in a separate module.

**Comment by banks** [comment]
Yeah. My feeling is that this probably won't make it into the core for now as we are concentrating on getting the API solid and the features together. This looks like an excellent 'helper' module could be written around this if it turns out that a very large proportion of users find this syntax useful as a separate module I guess there would be an argument for merging it into the core. Up to Jon though whether he thinks this should go into the core for now.

**Comment by jonathangeiger** [comment]
I agree. My initial though was that we may be able to use some of this for #27, but I'll have to look into it more thoroughly.
