### ISSUE TITLE
Database Exception 1140

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#111]
Database_Exception [ 1140 ]: Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause

Everything worked fine on my localhost. Now I'm porting it to the hosting firm's webspace and I recieve this error... :(

It happens on a page where I do this:

Jelly::select('newsitem')->open()->count()

**Comment by jonathangeiger** [comment]
Can you try updating to the latest commits and see if that helps?

**Comment by glamorous** [comment]
Hi Jonathan,

I will try this out tonight. The site is already live and I "fixed" it for now with hiding the pagination (where I do the above call) But I can test it in my testenvironment for the query. I can see if the query has changed or not... But how can I see my query because doing this:

```
echo Kohana::debug(Jelly::select('newsitem')->open()->count())
```

will return an integer I suppose, not the whole query?

**Comment by glamorous** [comment]
And wich commits do you mean? from Kohana Database of Jelly? (I will update them both and hopefully it's fixed :) )

**Comment by glamorous** [comment]
Looking at the code and the commit dates it will be fixed I think. I try it for certain this evening and close this issue. Thanks for the great work on Jelly! Is there a "release" date for 1.0?

**Comment by glamorous** [comment]
My fault, had to update... :) It was #95 that closes my issue, thanks!
