### ISSUE TITLE
export toArray, toXml, ...

### ISSUE THREAD

**Issue by Koc** [jonathangeiger/kohana-jelly#112]
Hello. Magento's models for collection have cool methods `toArray` and `toXml`:

```
$array = $myModel->getCollection->toArray();

/* now array contain smth like this:
'totalCount' => 100500
'items' => array(
    array('id' => 30, 'title' => 'item 30'),
    array('id' => 39, 'title' => 'item 39'),
    array('id' => 40, 'title' => 'item 40')
)
*/
```

Also I propose add possibility register my own Exporters:

```
Jelly::registerExport(new my_Exporter_Json);
$myModel->getCollection->toJson();
```

ps: sorry I don't know how add label for ticket.

**Comment by banks** [comment]
> ps: sorry I don't know how add label for ticket.

Only admins can!

I think this is outside of the remit of an ORM personally. If you really need to be able to convert lists to XML use an XML library. You could even write a specific module to convert Jelly_Collections into XML documents if you want but this is not something the core ORM should be concerned with or bloated by.

> Also I propose add possibility register my own Exporters:

Write a separate module. Jelly is an ORM (object mapping for the database) not a database export tool.
