### ISSUE TITLE
Timestamp field suggestion

### ISSUE THREAD

**Issue by gerasim** [jonathangeiger/kohana-jelly#113]
If timestamp field is formatted (for example, format='Y-m-d H:i:s' ), update for this field lead to error

> ErrorException [ Notice ]: A non well formed numeric value encountered 
> (Class Jelly_Field_Timestamp, method save() )

I suggest to add check in a method, whether value is already formatted

<pre>
// Convert if necessary
if ($this->format <b>AND (FALSE === strtotime($value))</b> )
{
    $value = date($this->format, $value);
}
</pre>

**Comment by jonathangeiger** [comment]
Closed by 2a72ba1c465e1330405468b69a2975be178c7157. Thanks gerasim!
