### ISSUE TITLE
conditions in the collections

### ISSUE THREAD

**Issue by ginad** [jonathangeiger/kohana-jelly#115]
I have a model author and has many posts
is it possible to do: 

<pre>
$a = Jelly::select("author");
// is this possible
$a->where("type","=","general")->posts;
// or 
$a->posts->where("type","=","general");
// or user ordery_by
$a->posts->order_by("id","DESC")
</pre>

Thanks

**Comment by smgladkovskiy** [comment]
try this

```
$a->get('posts')->where('type', '=', 'general')->order_by('id', 'DESC')->execute();
```

**Comment by smgladkovskiy** [comment]
I think that it is preferred to ask such questions on the Jelly Forum:
http://dev.kohanaframework.org/projects/jelly/boards

**Comment by banks** [comment]
Correct answer above, general questions should be in the forums rather than here.
