### ISSUE TITLE
Jelly_Builder_Core function - function unique_key issue

### ISSUE THREAD

**Issue by kaltar** [jonathangeiger/kohana-jelly#117]
Jelly_Builder_Core
Line: 195
    public function unique_key($value)
Shouldn't this be
    public function unique_key($value = NULL)

If it's to be overloaded by builders, could be fine, but what other way exists to retrieve the primary_key from a builder? Example:

$model_primary_key = Jelly::select('book')->unique_key(); 
// THROWS ERROR
$model_primary_key = Jelly::select('book')->unique_key('anything will do'); 
// RETURNS PRIMARY KEY

Edit: Spell checked.

**Comment by jonathangeiger** [comment]
This method isn't meant to simply return the primary key. If you [extend your builder class](http://jelly.jonathan-geiger.com/docs/jelly.extending-builder) you can override unique_key to return different columns based on the value passed.

For example:

```
Jelly::select('user', 1);
=> unique_key returns 'id' for the where clause, since 1 is an integer

Jelly::select('user', $username);
=> unique_key returns 'username' for the where clause, since $username is a string
```

**Comment by kaltar** [comment]
Thanks Jonathan.
Then, how can I retrieve the Model's primary key from a Jelly_Builder
Im implementing Jelly to my Datagrid before releasing it, and I want it to accept a Jelly_Builder as parameter, but I need to extract from it the primary key. I also posted a few questions on the Jelly Forum

http://dev.kohanaframework.org/boards/13/topics/433

But no response :(

**Comment by banks** [comment]
Please see my reply on the forum. Sorry - I've been away for a week and I know Jon is still working for his finals.
