### ISSUE TITLE
_is_unique(Validate $data, $field) error handling and i18n support

### ISSUE THREAD

**Issue by manact** [jonathangeiger/kohana-jelly#12]
I'm working with :
            catch (Validate_Exception $e)
            {
                $errors = $e->array->errors('forms/login/validate'); 
            }
wich gives me:
"Forms/login/validate.email.unique" at the output.
How can it be handled to support a validate message that can be used by i18n?
Like  'unique' => ':field can not be used. Please use another' or something more casual.
Thanks

**Comment by banks** [comment]
As far as I can tell, this is not an issue with Jelly - can you clarify what you are doing and whether it is really Jelly's probelm or if Validate doesn't work as you wish.

**Comment by manact** [comment]
As far as I can see, 'unique' is treated by Jelly not like the 'rules'.
class Model_Auth_User extends Jelly

```
        'username' => new Field_String(array(
            'unique' => TRUE,
            'rules' => array(
                    'not_empty' => array(TRUE),
                    'max_length' => array(32),
                    'min_length' => array(3),
                    'regex' => array('/^[\pL_.-]+$/ui')
                )
            )),
```

Jelly/Core

```
public function _is_unique(Validate $data, $field)
{
    if ($data[$field])
    {
        $count = Model::factory($this->model)
                    ->where($field, '=', $data[$field])
                    ->count();

        if ($count)
        {
            $data->error($field, 'unique');
        }
    }
}
```

The 'rules' error messages are well referenced in the message file 'forms/login/validate' like this ''not_empty'    => ':field must not be empty', ...'
Validation takes care of the i18n output placed in /application/i18n/fr, en, es, ... as a result a translated error like : 'nom d'utilisateur ne peut être vide'.
It seems that '_is_unique' in Jelly/Core doesn't refer : 
neither to the message file for the default message I'd like to throw in that case ('unique' =>':field must be unique') 
neither to the i18n translation ':field must be unique' => ':field doit être unique'
before to add to the validation error array().
Thanks

**Comment by dewos** [comment]
For me, unique should be an extra rule, not a field propriety.

**Comment by jonathangeiger** [comment]
Just add a message for 'unique' in one of your messages files. It's not really Jelly's job to handle your messages.

**Comment by jonathangeiger** [comment]
@Dewos

It would make more sense, but it's just not possible the way the Validate class works.

**Comment by manact** [comment]
Just to point that I use the models of the jelly-auth of raeldc
http://github.com/raeldc/jelly-auth
@Dewos
It can't be full part of validation because of the call to the orm (_is_unique). The orm add (just add) the error to the Validation error.
@Jonathan
That's what I did and checked again. The message has been added this way in the message file:
'unique' => ':field must be unique...'
The same way other messages.
I will need an issue to this question and keep you adviced of my results.
Many thanks to follow.

**Comment by manact** [comment]
Ok Jelly send the error to Validate. But Validate does not treat the error like it was a rule. So normal rules search in message like this :
pathtomessage.max_length
and error sended by $data->errors($field, 'unique') like this :
pathtomessage.field.unique
So no way to make a unique message for all fields that require uniqueness.
Must be personalized by field.
Thanks
