### ISSUE TITLE
$null ignored by Field_BelongsTo

### ISSUE THREAD

**Issue by ghost** [jonathangeiger/kohana-jelly#124]
I have a model with a Field_BelongsTo set to 'null' => TRUE, but empty string '' is not converted to NULL. Problem lies in Field_BelongsTo.set(), the "Convert NULL values to the default" without respect to the $null parameter.

**Comment by jonathangeiger** [comment]
Closed by c1d887d15cd4bf378d25d62f20e6a3f2f5105a91. Thanks nekofs!
