### ISSUE TITLE
Field_Serilized - Serialized empty string does not unserilize

### ISSUE THREAD

**Issue by lemonskip** [jonathangeiger/kohana-jelly#127]
Hi,

Jelly_Field_Serialized line 29 reads: if ($return = @unserialize($value))

But should read: if( ($return = @unserialize($value)) !== FALSE )

Logic: unserialize('s:0:"";') returns '' which is == to false but is not equal to !== false

This needs changing as my empty fields return: s:0:""; in oppose to ''

Thanks

M

**Comment by jonathangeiger** [comment]
Closed by cb806524f5fc1e3a545f50a52de6f0b4bccbfd85. Thanks lemonskip!
