### ISSUE TITLE
as_array() on Jelly_Model throws this error...

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#128]
![Jelly Error](http://dl.dropbox.com/u/1051568/images/jelly-error.png)

What seems to be causing this error? Even the simplest code throws it:

Jelly::select('model', $id)->as_array();

...

**Comment by jonathangeiger** [comment]
Can you post your actual code?

**Comment by raeldc** [comment]
Sigh... Just figured it out. I was referencing a non-jelly model in my belongsto field. Lesson learned, don't code when you should be sleeping.

**Comment by jonathangeiger** [comment]
I figured that's what it was.
