### ISSUE TITLE
[Bug] Table prefix is appending wrongly

### ISSUE THREAD

**Issue by jip** [jonathangeiger/kohana-jelly#129]
for Jelly d8d0bdd1714e5ed5ad231d18c6097a4843946e5f

=== model/device.php : ===

```
class Model_Device extends Jelly_Model
{
    public static function initialize(Jelly_Meta $meta)
    {
    $meta->table('devices')
        ->fields = array(
            'id' => new Field_Primary,
            'place' => new Field_String,
            'dstate' => new Field_BelongsTo(array(
                'foreign' => 'dstate.id',
                'column' => 'state_id',
            )),
        );
    }
} // End Device Model
```

=== model/dstate.php : ===

```
class Model_Dstate extends Jelly_Model
{
    public static function initialize(Jelly_Meta $meta)
    {
    $meta->table('dstates')
        ->fields = array(
            'id' => new Field_Primary,
            'title' => new Field_String,
        );
    }
} // End Dstate Model
```

Tables have the prefix 'c_'. I want to get device places from table 'c_device' and state titles from reference table 'c_dstates' together:

SELECT c_devices.place, c_dstates.title FROM c_devices LEFT JOIN c_dstates ON (c_devices.state_id = c_dstates.id)

My controller:

=== controller/device.php : ===

```
class Controller_Device extends Controller_Template
{
    public function action_index()
    {
        // get data from db
        $devices_builder = Jelly::select('device')
            ->select('place')
            ->with('dstate')
            ->select('dstate.title')
            ->execute();
    }
} // End Device Controller
```

But the following exception occures:

Database_Exception [ 1054 ]: Unknown column 'c__dstate:dstate.id' in 'field list' [ SELECT `c_devices`.`place`, `c_devices`.`id` AS `id`, `c_devices`.`place` AS `place`, `c_devices`.`state_id` AS `dstate`, `c__dstate:dstate`.`id` AS `:dstate:id`, `c__dstate:dstate`.`title` AS `:dstate:title`, `c__dstate:dstate`.`title` FROM `c_diosks` LEFT JOIN `c_dstates` AS `_dstate:dstate` ON (`c_diosks`.`state_id` = `c__dstate:dstate`.`id`) ]

in MODPATH/database/classes/kohana/database/mysql.php [ 178 ]

**Comment by banks** [comment]
Please format your comments better - all code should be indented with at least one tab!

I don't have time to pick through this now, we will look later but if you could reformat your question it would make it much easier to help you!

**Comment by banks** [comment]
I can't see where the extra underscore comes from in the alias. Are the aliases set up in the Database module? If so, which driver are you using?

**Comment by jip** [comment]
Sorry for bad formatting. Code is indented now.

I don't quite clearly understand how to set up aliases in Database module. IIRC, I hadn't do it. Database module's config is standart but has option:
'table_prefix' => 'c_',
driver is MySQL.

**Comment by banks** [comment]
I'm not sure what is going on here. Hopefully one of us will get a chance to look at this some time soon - we are both a bit snowed under. Any more information/debug print outs you can share will probably help us.

**Comment by glamorous** [comment]
Did you updated the latest database commit because there was a little mistake here where the fix was deleted again... see http://dev.kohanaframework.org/issues/2780 and the fix at http://github.com/kohana/database/commit/da380c096f0ad1a81c96f191ba25f3b800ce61d2
