### ISSUE TITLE
"Null" value in Field_Timestamp

### ISSUE THREAD

**Issue by gerasim** [jonathangeiger/kohana-jelly#131]
Hello!

I suggest change the file views/jelly/field/timestamp.php from

<pre>
echo Form::input($name, date($pretty_format, $value), $attributes + array('id' => 'field-'.$name));
</pre>

to

<pre>
echo Form::input($name, (!isset($default) && !isset($value))?'':date($pretty_format, $value), $attributes + array('id' => 'field-'.$name));
</pre>

elsewise I get a date (1970-01-01) in a form's field even if a default value declared explicitly as null (also parameter 'null'=>true), e.g.

<pre>
'myField' => new Field_Timestamp(array(
    'format' => 'Y-m-d',
    'pretty_format' => 'Y-m-d',
    'null' => true,
    'default' => null,
)),
</pre>

**Comment by jonathangeiger** [comment]
Closed by 4d9fe90334749e536239ab8dd9d3ea3a1193f151. Thanks gerasim!
