### ISSUE TITLE
return model validation errors

### ISSUE THREAD

**Issue by ogyr** [jonathangeiger/kohana-jelly#135]
it would be nice to have a method errors( $message_file = NULL ) on a Jelly_Model, returning the errors that would trigger the Exception from within save();

So one can do:

```
$my_model->set($values);
if( $errors = $my_model->errors($custom_messages) )
{
     //display errors here
     print_r($errors);
}
else
{
    //will not fail validation
    $my_model->save();
}
```

What do you think? It would be easy eg by changing the validate method signature to

```
public function validate($data = NULL, $return_errors = FALSE, $messages_file = 'validate' ) 
```

and adding the function:

```
public function errors($data = NULL, $messages_file = NULL)
{
    return $this->validate($data, True, $messages_file);
}
```

Any thoughts on this?

**Comment by ccazette** [comment]
100% agreed. The only workaround I've found at the minute is to catch Validate_Error $e and to call $e->array->errors().

**Comment by jonathangeiger** [comment]
What's wrong with using try/catch?

**Comment by ccazette** [comment]
Nothing wrong. But it took me a little while to find out that this was the only way to retrieve validation errors. $e->array->errors() sounds more like a workaround to get an information that is pretty crucial. It works fine so I am not bothered about it, as long as it will be documented somewhere when releasing.

**Comment by ogyr** [comment]
Yes, I overlooked the possibility to call $e->array->errors(); Some note in the docs might help.
A minor thing though when using validate(): I see that at the beginning of save() you have:

```
$data = ($this->_loaded OR $key) ? $this->_changed : $this->_changed + $this->_original;
```

but within validate() you only take:

```
$data = $this->_changed;
```

That means that Jelly::factory('mymodel')->set($values)->validate() does not throw an error if default model values do not comply with their rules (eg. not_empty). Is that intended?

**Comment by jonathangeiger** [comment]
I'm kind of iffy when I think about changing this because it's a rather large API departure. 

I suppose the following is nicer, though.

```
if ($model->save())
{
    // Save went well
}
else
{
    $errors = $model->validator()->errors('message/file');
}
```

**Comment by banks** [comment]
I think having access either way is fair enough. Something like what you just posted jon seems logical.

I think the default interaction should remain as it is through exceptions but allow public access to the validation object (through `validator`) for maximum flexibility.

**Comment by ccazette** [comment]
@banks, jon

I missed the validator() method somehow. I agree, then, that is enough and makes sense the way it is.

**Comment by jonathangeiger** [comment]
validator() is protected now. I'll make it public.
