### ISSUE TITLE
Jelly database generator

### ISSUE THREAD

**Issue by ckald** [jonathangeiger/kohana-jelly#136]
I suppose, everyone is thinking about full coding-less modularity for our projects. You just login as admin, check some modules, and they are installing: creating database tables setting up routes and so on.

It would be nice, if Jelly could generate some SQL code basing on the model (through database drivers)

**Comment by bmidget** [comment]
You could certainly make a module that'd do what you're suggesting.

I think adding this to Jelly itself is too much bloat.

**Comment by ckald** [comment]
Okey, I'll report somewhere on result

**Comment by jonathangeiger** [comment]
Looks like ollym has a Jelly driver for his migration module. Is that what you're looking for?

http://github.com/ollym/migration

**Comment by ckald** [comment]
Fantastic, that is it. Sorry, I didn't notice.
The only problem is huge amount of very different code type (one type by commiter) in any smallest project) I will have many work on refactoring
