### ISSUE TITLE
It's Pretty!

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#14]
This is a pretty insignificant issue. 

I just find it funny that you're using `pretty_true` and `pretty_false` for Field_Boolean. Why not just 'label_true' and 'label_false' to make it more "formal". :)

Anyway, it's always your choice Jonathan! I'm happy to follow.

Thanks!

**Comment by jonathangeiger** [comment]
I'll fix this in the upcoming version.

**Comment by jonathangeiger** [comment]
Fixed here:

http://github.com/jonathangeiger/kohana-jelly/commit/8e5ea6997aed6db1e707144abf07e53d2eeef4fd#diff-5

This will be merged to master in a couple of days or so.
