### ISSUE TITLE
Strict Exception

### ISSUE THREAD

**Issue by dewos** [jonathangeiger/kohana-jelly#142]
->save() or ->check() get:

ErrorException [ Strict ]: Declaration of Jelly_Core_Validator::check() should be compatible with that of Kohana_Validate::check()

Bye!

**Comment by dewos** [comment]
Exception error fixed by http://github.com/agentphoenix/kohana-jelly/commit/09157e2f4eb4186f49a66097fa0941251a2ec82c#diff-0

**Comment by jonathangeiger** [comment]
Closed by 9b01206690bbbc15fcf4c3d61c4b21ea29417816
