### ISSUE TITLE
Serialized field and null values

### ISSUE THREAD

**Issue by Neurergus** [jonathangeiger/kohana-jelly#143]
Hi,

I have a serialized field with the options allow_null and convert_empty set to TRUE, but even if I set the field to null, it saves something like "N;" (php serialized representation of null, I suppose :S).

I've modified the save function to temporarily circumvent this:

```
public function save($model, $value, $loaded)
{
    return $value ? @serialize($value) : $value;
}
```

At least it's working for my case :-)

**Comment by jonathangeiger** [comment]
Should closed by 1481e2922e9e17a4c8c01c2ceb0c1e194f9b9d24
