### ISSUE TITLE
join on value

### ISSUE THREAD

**Issue by sartor** [jonathangeiger/kohana-jelly#144]
I want to left join table on two conditions:
1. foo.id = bar.foo_id
2. bar.baz = "my_value"
Result query must look like:
SELECT \* FROM `foo` LEFT JOIN `bar` ON (`bar`.`id_foo` = `foo`.`id` AND `bar`.`baz` = "my_value")
But now all ON conditions escaping and this prevent to join on value.
I see solution like
Jelly::select('foo')->join('bar', 'LEFT')->on('bar.id_foo', '=', 'foo.id')->on_value('bar.baz', '=', 'my_value')->execute();
Sorry for my bad english.

**Comment by banks** [comment]
The correct way to do this is to use a Database Expression to prevent escaping. This isn't really a Jelly issue - this is a fundamental in the way Kohana Query builder works. If you feel it should change, then I'd suggest you post this as a feature request on the Kohana 3 bug tracker. I don't think we want to start adding non-Jelly related functionality to Query builder just for convenience.

Current Solution:

```
Jelly::select('foo')
    ->join('bar', 'LEFT')
    ->on('bar.baz', '=', DB::expr('"string value"'))
```

Note that you effectively have to do your own escaping in the database expression but that should be protected from being quoted as a column identifier. If you don't know the type of the value, you can use Database's quote method to perform the same logic you would get when entering a value into where() or similar.
