### ISSUE TITLE
Chaining Builder

### ISSUE THREAD

**Issue by dewos** [jonathangeiger/kohana-jelly#146]
```
// Works
$nodes = Jelly::query('node')->select();

// Fails
$nodes = Jelly::query('node');
$nodes->select();
```

**Comment by leth** [comment]
I have a suspicion that this is just the way jelly works.

Does the following perform correctly?

```
$nodes = Jelly::query('node');
$nodes = $nodes->select();
```

**Comment by dewos** [comment]
Thanks leth, it works. By the way, this really seems like a bug to me .

**Comment by leth** [comment]
I'm guessing that before you call select you're working with a query builder object, and after you're dealing with either an instance of the model or a collection thereof.

I can see why it's confusing (especially if you've used the ORM module), but separating things in that way makes the code a whole lot more modular.

**Comment by dewos** [comment]
Ok, then i close this and add it on docs request. Thanks again.
