### ISSUE TITLE
Github feature request

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#15]
Is it possible to use labels for all issues? It's easier to read as a user. When their are more issues than now, everyone should see easily if it's a bug, a feature request...

For example:
label "bug" => red
label "feature request" => green
label "to consider" => yellow

maybe "planned", "in progress"

Think about it ;-)

**Comment by banks** [comment]
I've never even seen the labels before! We can give it a go...

**Comment by banks** [comment]
Looks helpful thanks. I'm going to close this now.

Jon, we could even potentially look at designating work using 'banks' and 'jon' labels... What do you reccon.

**Comment by glamorous** [comment]
I think even users can use this labels so it's easier for you guys to know if it's a bug or something else... More info about issues and labels and so on: http://github.com/guides/working-with-the-issue-tracker

**Comment by jonathangeiger** [comment]
This man's a genius.

**Comment by glamorous** [comment]
Another thing that's useful: If you use the words "closes #1" in your commit-message, github will automaticly close the issue on github and provide a link from the message to the issue so people can see what the issue was... An example: http://github.com/glamorous/jQuery-Google-Analytics/commit/fe0b0b3b1ded3ac5f4cedd59e33378853d656bf9

(see in the movie from my previous comment)

**Comment by banks** [comment]
Thanks for that - I knew about that one actually. It is rarely useful to me though because the commit that fixes an issue is normally in an unstable branch and I don't want to close the issue until the fix is merged into the master branch. Of course when it is merged, git automatically adds the commit message so it is less hassle to manually close...

**Comment by glamorous** [comment]
Want to hit this issue once again now there raising more and more bugs... It's just a word change: use "Closes #1" instead of "Fixes #1" Because for now we have to search the issue to see what is was... If you guys use the correct syntax it's easy to see for other people (like me) what the issues was...

**Comment by jonathangeiger** [comment]
I was wondering why it wasn't working...
