### ISSUE TITLE
Model global filter / rules / callbacks

### ISSUE THREAD

**Issue by zsoerenm** [jonathangeiger/kohana-jelly#152]
The implemented validation in KO3 suppoerts global filters etc. like:
    $post->filter(TRUE, 'trim');
As it is very useful, I suggest you support it too. Although right now I can't see a simple solution for this. Maybe there is some work going on regarding this to version 1.0?

**Comment by banks** [comment]
Are you using the unstable code? That is not by any means finished and work has halted somewhat on the validation front until we hear what the Kohana devs plan to do with Validation generally in 3.1. We really don't want to be developing our own version of it but the basic one is just not flexible enough and there has been discussion about changing it for a while.

**Comment by banks** [comment]
I'm going to close this as validation _will_ change in Jelly one way or the other before it is considered released and production ready.
