### ISSUE TITLE
Question about Jelly_Builder

### ISSUE THREAD

**Issue by kaltar** [jonathangeiger/kohana-jelly#158]
I think there is no way to extract the model name from a builder. Is it possible to add a method to extract it?

**Comment by banks** [comment]
Can you give an example why you would need this? In most cases the objects being returned will be enough to work out what they are!

Still it is very simple so if there is a useful case then it probably will go in.

**Comment by kaltar** [comment]
Hey Banks,
Been working on a module for many months now. I made a Jelly driver that can take a jelly model name or a jelly_builder as argument on a method. A builder is a great way to pass a model without having to re-create a builder or extending Jelly's one. 

```
$rules = Jelly::select('rule')->where('building_id', '=', $id);

$grid = Datagrid::jelly()
    ->set_model($rules)
    ->render();
```

I use Jelly's builders because: it HAS the model information! It's there... maybe I cannot access it right now, but it's there! I think there should be a way to extract model name (and other meta data) from a builder, since the builder knows about that model. probably something like meta(), but in the builder. Only that way we would really use the full potential of it!

Also, I know this is a deficiency of kohana's query builder, but there is no way to reset just certain things on a builder, like the select or order_by. Probably an argument on Jelly's builder's reset() that asks for the section to be reset? (Jelly's builder's 'count()' does this... but just for that function! ) or also, a way to Extract those fields: _select, order_by, etc... There is no way to get info from a builder!

**Comment by banks** [comment]
A `meta()` function is probably esy ewnough to add to builder and I can see a case for it.

I'm not sure where Jon is going with the new API though so I can't say when this will happen (I've not heard from him for a while now). In the interim, you could always transparently override Jelly_builder in you module and ensure your module is included first!

**Comment by kaltar** [comment]
Thanks Banks.

What about access to  _select, order_by? any function to get/set (since currently it appends)?

**Comment by banks** [comment]
> access to _select, order_by

I'm not so sure. There is a good reason for encapsulation like this. If we effectively make everything 'public' it will no doubt cause problems. I think the thing is, the query builder object is not designed to be a transparent holder of information about a query that you can manipulate as you like. It is designed (like the Query builder it extends) to encapsulate query building logic. If you need something that allows arbitrary public storage and retrieval or properties of a set (what to select, ordering etc) a query builder just isn't the right object to use even if it does have the info you need in it.

I think you need to review exactly what data access you need in your library and either find a way to make it work with Query builder (without needing to completely change what query builder does) or write your own obect to encapsulate the behavior you need.

You might for instance have an object which has a similar interface for setting up the query but exposes parts of that as required and then compiles all the options into a real query builder at the last minute.

You may even just extend query builder transparently and add in the additional access you want but I think adding public access to everything completely changes the nature of the object and is probably not a good idea in general.

**Comment by jonathangeiger** [comment]
meta() is public in unstable. I'm focusing on the unstable branch right now and I can't make any guarantees I'll go back and add it to the old version of Jelly.

**Comment by kaltar** [comment]
Great!!
