### ISSUE TITLE
Unique key check fails if string's case is altered

### ISSUE THREAD

**Issue by justus** [jonathangeiger/kohana-jelly#161]
Using raeldc's Jelly-Auth, when accidentally tried to change username to uppercase, got a validation error pointing at username-field's is_unique check. This seemed a bit odd. Unique key should be checked against all other records, not the one that is being updated, right?

EDIT: Seems that this was a MySQL collate thing, didn't know string searches were case insensitive

**Comment by jonathangeiger** [comment]
This has been fixed in the unstable branch.
