### ISSUE TITLE
Feature Request: Jelly_Collection method to get array of arrays

### ISSUE THREAD

**Issue by humaninternals** [jonathangeiger/kohana-jelly#163]
Any chance you could add a function to transform a Jelly_Collection into an array of arrays, where each row is an array? This is useful, for example, for json_encode()ing multiple rows, passing it to external libraries that expects an array of arrays and doesn't know how to handle Jelly_Model instances, etc.

For example, `Jelly::select('blogpost')->execute()->some_method();` would return `array(array('id'=>123,'title'=>'Hello world'), array('id'=>456, 'title' => 'Lorem ipsum'))`. Basically, each row is called with `as_array()` too to get a real array representation of a Jelly_Collection.

**Comment by jonathangeiger** [comment]
I would say this should be done in your code and not in Jelly.

**Comment by humaninternals** [comment]
Yes, that's a possibility, and that's what I've done so far. I do think its an operation that's common enough to get into core, but its not a must.
