### ISSUE TITLE
Fatal error: Only variables can be passed by reference

### ISSUE THREAD

**Issue by crackcomm** [jonathangeiger/kohana-jelly#191]
Fatal error: Only variables can be passed by reference in classes/jelly/core/builder.php line 948:

---

```
extract($this->_meta_alias($field, array(
            'model' => $model,
            'field' => $field,
            'value' => $value,
)));
```

should be:

```
$variable = $this->_meta_alias($field, array(
            'model' => $model,
            'field' => $field,
            'value' => $value,
));
extract($variable);
```

**Comment by nickolasgregory** [comment]
You should probably post this issue here;
    https://github.com/creatoro/kohana-jelly-for-Kohana-3.1/
as this repo is no longer maintained.

**Comment by bistory** [comment]
It's a pitty that only the unstable branch is still maintained, there is a lot of people that are still using the master branch and have to keep that version running instead of upgrading.
And I prefer the syntax of the master branch...

**Comment by crackcomm** [comment]
sry i thought it was that branch...x/
