### ISSUE TITLE
save() should trigger validation()

### ISSUE THREAD

**Issue by dewos** [jonathangeiger/kohana-jelly#2]
See title :)

**Comment by banks** [comment]
I agree actually.

**Comment by jonathangeiger** [comment]
How should this be handled? Should an exception be thrown? Should save() return a boolean? I'll definitely add this but I want to hear some opinions on how the API should work.

**Comment by dewos** [comment]
Save just call check().
Validation Class throws the exceptions (if any).

**Comment by jonathangeiger** [comment]
The validation class doesn't throw any exceptions on failure.

**Comment by dewos** [comment]
```
    if ( ! $data->check())
    {
        throw new Validate_Exception($data);
    }
```

**Comment by banks** [comment]
Fixed in branch: [commit](http://github.com/jonathangeiger/kohana-jelly/commit/67ce5e16d4acbd736b5f0ab8e038fbe771634a7f).

Jon, can you merge this to master and close when you are happy with it. (Note I have not tested this exhaustively but I'm fairly sure it will work as expected.)
