### ISSUE TITLE
Commits with github account

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#20]
I don't know if it's possible but I should be a lot clear if Paul Banks pushed his changes with his github-account instead of a personal account. I think that's the reason why when you click on "network" you can't see the branch from paul_banks.. As a follower of this project it's nice (and cool) to see what's been done, merged, ... and where every developer branch is over the "master", were it's get merged ...

Don't feel required to do this but it should be cool/nice :)

Keep up the good work!

**Comment by banks** [comment]
> Paul Banks pushed his changes with his github-account instead of a personal account

I do... I'm not sure what you mean, I only have a github account and I push stuff here in exactly the same way as anywhere else.

My dev branch has actually not been used yet! I've pushed a few things but Jon has always finished the code straight away. I've also deleted and recreated the banks_dev branch a couple of times as it got out of date and I did a whole load of work we decided not to use so it was easier to recreate than revert and merge etc.

If I've done something wrong, please let me know and I'll try to sort it - very little of my code has actually got onto github yet - it is mostly ideas from me and action from Jon at the moment.

**Comment by glamorous** [comment]
I do not think that it's only you Paul. If you look at the commits you can see 4 commiters ( http://github.com/jonathangeiger/kohana-jelly/commits/master ) :
 jonathangeiger (linked to: http://github.com/jonathangeiger ), banks (linked to: http://github.com/banks ), Jonathan Geiger (no link), Dewos (linked to: http://github.com/Dewos )

For now I can't find a commit with no link wit your name but I don't know what the problem is. Maybe a different author on different machines (other emailadres that's not connected to a github account or so...)

**Comment by banks** [comment]
Hmmm. You won't have seen my branch in the network graph before because I never had commits that weren't already i another branch (because Jon merged them so fast) and the network graph will only show a particular commit once the first time it comes across it. If you look now and scroll to the right you will see my branch is a few commits ahead of unstable. I'm not quite sure I see a problem other than Jon once committed from a different account by mistake...

**Comment by jonathangeiger** [comment]
Yea, once or twice I was on another computer that wasn't set up with the right email address.
