### ISSUE TITLE
Links in banks_dev guide returns 404

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#21]
The links return a 404, looks like the extension isn't provided in the link (when I manually add the extension, it works...)

ps. Sorry for the "many" issues :)

**Comment by banks** [comment]
Which links?

**Comment by banks** [comment]
> when I manually add the extension, it works

You should not need an extension. Perhaps you have an older version of userguide?

**Comment by glamorous** [comment]
I'm looking the stuff at github, maybe that's the problem? (it are the links from the guide)

(I definitely need to download this project local :) )

**Comment by banks** [comment]
The links (and documentation) are designed to be displayed in Kohana's userguide. They won't work in the github previews!
