### ISSUE TITLE
Bug in Line 257 of Jelly_Builder_Core

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#26]
Parent doesn't have the select_array() method.

`return parent::select_array($columns);`

Is it supposed to return just the `$columns`? `select_array` seems to be found only on Jelly.

**Comment by jonathangeiger** [comment]
Is this throwing an error or are you just making an observation? select_array() is defined in Kohana_Database_Query_Builder_Select, which Jelly_Builder_Core extends.

**Comment by raeldc** [comment]
Sorry I was using an old database module from Kohana 3.03 package. It seems that the select_array() method is something new.

**Comment by jjlegendre** [comment]
Where can I download the latest build of the database module?  I'm having this error now.

**Comment by banks** [comment]
[github](http://github.com/kohana/database). Use the master branch from there NOT the commit that the default kohana app is pointing to.
