### ISSUE TITLE
Allow convenient, single query deleting of all models in a collection

### ISSUE THREAD

**Issue by banks** [jonathangeiger/kohana-jelly#27]
Something like

```
Jelly::select('user', 1)->roles->delete();
```

Would be equivalent of

```
Jelly::delete('role')->where('user_id', 'IN', $user_collection->ids())->execute();
```

This could internally be done by making `where('column', '=', $jelly_collection_instance)` map to `where('column', 'IN', $jelly_collection_instance->ids())`. This would solve the first part of the eager loading problem simultaneously.

Not sure whether including a `delete()` method in `Jelly_Collection` is sensible. It breaks the API separation a bit since the collection now has query building. Perhaps make this work instead:

```
Jelly::delete($collection)->execute();
```

**Comment by raeldc** [comment]
I agree that it's inconsistent to put `delete` in `Jelly_Collection`.

And yup I think the best way to implement it is through your last suggestion:

`Jelly::delete($collection)->execute();`

**Comment by jonathangeiger** [comment]
Another solution that would be simpler would be this:

```
Jelly::select('user', 1)->get('roles')->delete();
```

We could just add a delete() convenience method to the query builder. We already have load() as it is.

**Comment by banks** [comment]
Clearly that is the most API consistent way Jon. Good thinking.

**Comment by banks** [comment]
After A LOT of discussion, this will be implemented in a more general solution where any query type can be built for related models with no intermediate query. Any other way was a nasty hack in the query API.

The following syntax will be implemented:

```
// Select all roles for a given user ID with 1 query (no user loaded)
Jelly::select('user.roles')->for_key(1)->execute();

// Delete all roles for a given user in 1 query without having to load (or reload) the user
Jelly::delete('user.roles')->for_key(1)->execute();

// Update all tickets related to a project older than 1 month to be inactive
Jelly::update('project.tickets')
    ->for_key('Project 1')
    ->set(array('inactive' => 1))
    ->where('last_update', '<', strtotime('-1 month'))
    ->execute();
```

Note in all above cases, only a single query is required. Also note that for select() this does NOT load the parent model (see eager loading ticket), only the children for a given parent ID

**Comment by glamorous** [comment]
Wow that's great solution, better for performance. Thumbs up!

**Comment by ccazette** [comment]
So is this another way of doing this : 
`Jelly::delete('roles')->where('roles.user:foreign_key', '=', 1)->execute()`
?
If so, I don't really see why it's worth implementing something similar, that could possibly end up confusing the API... I might miss something though, as you have apparently put lots of thoughts into this ?

**Comment by banks** [comment]
Your example is slightly in correct. 

You are confusing fields and models which is one thing this syntax makes clearer, your example should be

```
Jelly::delete('role')->where('role.user:foreign_key', '=', 1)->execute();
```

I know that is a very minor point but actually I think it is something that will potentially cause people confusion as you need to refer to the model not the relationship.

The other point is that you have assumed a one-to-many relationship when actually it is likely to be a many-to-many. In the many-to-many case the difference in sytax is much more pronounced.

```
// Current way
Jelly::delete('role')
    ->join('roles_users')
    ->on('role.users:foreign_key', '=', 'user.roles:foreign_key')
    ->where('user.roles:foriegn_key', '=', 1)
    ->execute(); // Note that this is probably wrong - I couldn't even work out quickly which keys to put where

// New way
Jelly::delete('user.roles')->for_key(1)->execute();
```

Not only is it shorter but it means you aren't duplicating the relationship logic defined in the field models. So if you switch your model definition to use many to many rather than one to many or if you use a custom relationship field which has much more complicated join logic, the same syntax will still work with no duplication of code.

Does that make more sense?

**Comment by banks** [comment]
Jon, You have a lot of things going on with NULL values and aliasing and all. Do you want me to take this on or have you already got your head around it?

**Comment by jonathangeiger** [comment]
I think it should be saved for 0.9.7 or 1.0.0. I'm leaving 0.9.6. for bug fixes.

**Comment by jonathangeiger** [comment]
This is fixed in unstable. Closing for now.
