### ISSUE TITLE
Bug in line 43 of Jelly_Collection_Core (method: as_array)

### ISSUE THREAD

**Issue by memakeit** [jonathangeiger/kohana-jelly#29]
The error message I am receiving is:
ErrorException [ Notice ]: Undefined variable: model

Line 43 should be changed from:
$meta = Jelly::meta($model);

to: 
$meta = Jelly::meta($this->_model);

Thanks for all of your work on Jelly.

**Comment by raeldc** [comment]
Pull the latest commits. It's closed already as issue#24.

**Comment by memakeit** [comment]
Ok.  Thanks.
