### ISSUE TITLE
Support composite primary keys

### ISSUE THREAD

**Issue by banks** [jonathangeiger/kohana-jelly#3]
As discussed

**Comment by jonathangeiger** [comment]
Hoping we could get some discussion regarding this. Is there a real impetus to get these working? Looking through the code, it seems like it would add a fair bit of complexity—especially when it comes to relationships—for a fairly small feature. 

Additionally, there's gonna be a lot of boilerplate written in the builder to check and see if the primary key meta alias needs to be expanded.

**Comment by banks** [comment]
Yeah. I'm not so sure now either to be honest. There are certainly situations where this is  important as a feature but it seems no one who is currently using Jelly really has a need for this - if I'm wrong please comment. I'd like to get this in at some point but perhaps it could be better left for later.

I know we said it would be easier to implement now rather than later but to be honest it will take quite an effort now so I'd rather concentrate on features that are more likley to be useful to people.

**Comment by jonathangeiger** [comment]
Banks and I have decided to drop this for the time being. There are more important features we'd like to focus on.

**Comment by humaninternals** [comment]
I personally always add an single-column auto increment primary key to my tables, mostly to have a unified way of identifying rows (in a generic CRUD controller, for example), so I personally don't need a composite primary key.
