### ISSUE TITLE
$value in Input Views

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#30]
I haven't looked into the code to check the real cause, but it seems that `$value` is not passed to the input view if the object is blank or newly instantiated.

```
**ErrorException [ Notice ]: Undefined variable: value**

<input type="text" name="<?php echo $name?>" value="<?php echo $value ?>" id="field-<?php echo $name?>">
```

This happens when you use the input() for new objects.

**Comment by raeldc** [comment]
I think it would also be helpful to note that this happens when I use `Jelly::meta('model')->fields('myfield')->input()`

Edit:

This should now be a very minor issue or non-issue at all. I should just be using $field->input() instead of a non-conventional way.

**Comment by banks** [comment]
> I haven't looked into the code to check the real cause, but it seems that $value is not passed to the input view if the object is blank or newly instantiated.

Not suer I understand this. If you are showing inputs for a blank model $value should be default value which is NULL unless you have set it otherwise. Can you explain what you are expecting to happen and what is happening?

**Comment by raeldc** [comment]
This happened when I was experimenting with the new way to get metas. I was looking for ways to iterate through the fields to display a quick form. I guess I just took the wrong steps.

My code used to be like this:

```
<?php foreach (Jelly::meta('user')->fields() as $label => $field): ?>
    <p>
    <label><?php echo ucwords(Inflector::humanize($label)) ?></label> <br />
    <?php echo $field->input($label) ?>
    </p>
<?php endforeach ?>
```

The code above is the one causing problems. But I fixed it using this code:

```
<?php foreach ($fields->fields() as $label => $field): ?>
    <p>
    <label><?php echo ucwords(Inflector::humanize($label)) ?></label> <br />
    <?php echo $user->input($label) ?>
    </p>
<?php endforeach ?>
```

Where `$user` is a Jelly object.

If you think there's something wrong here, please enlighten me. 

Thanks!

**Comment by jonathangeiger** [comment]
You should be using the second example. It might be useful for us to add a way to get at a model's meta object so you could do something like this:

```
<?php foreach ($user->meta()->fields() as $label => $field): ?>
    <p>
    <label><?php echo $field->label ?></label> <br />
    <?php echo $user->input($label) ?>
    </p>
<?php endforeach ?>
```

Also, notice that the fields have a label property that you can set.

**Comment by banks** [comment]
I'm going to mark this as closed as there is no bug as such. If adding `meta()` as a method to `Jelly_Model` is a good idea we can do that or create a separate feature request.

**Comment by jonathangeiger** [comment]
Just want to note that I added the meta() method so that should make my example possible. This is probably the most elegant way to go about it.

feee1e86fd985f8c0978b580e43f957179cf37a3
