### ISSUE TITLE
Some leftover code from Jelly Field Views Jelly 0.9.5.3

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#31]
For all relationship field input views, the iteration is still:

`<?php foreach(Jelly::factory($foreign['model'])->load() as $related): ?>`

This should be:

`<?php foreach(Jelly::select($foreign['model'])->execute() as $related): ?>`

**Comment by jonathangeiger** [comment]
Closed by 9eb979fceb03b1122f3baadc073fc8c1975ac5a9. Thanks raeldc!
