### ISSUE TITLE
Meta-alias not converted properly when as_array is used  0.9.5.3

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#32]
Check this error:

![issue-32](http://dl.dropbox.com/u/1051568/images/issue-32.png)

I hope that's helpful already. I'm encountering this error when I save roles for a user.

**Comment by jonathangeiger** [comment]
Can I see your code? Meta-aliases only work in the query builder, not anywhere else.

**Comment by raeldc** [comment]
The strange thing is, I'm not really using meta-aliases. 

Upon further debugging, I found out that it's not really the saving of the relationships that causes the error. It's the removal.

You can use my jelly-auth models to test. You can replicate the error by that this simple code.

```
$user = Jelly::select('user')->load(1);
$user->remove('roles', 1);
$user->save();
```

**Comment by raeldc** [comment]
If I'm trying to delete all the roles, my code is like this:

```
$user = Jelly::select('user')->load(1);
$user->remove('roles', Jelly::select('roles')->execute());
$user->save();
```

**Edit:**
To make my code work, I had to do this:

`Jelly::delete('roles_users')->where('user_id', '=', $user->id)->execute();`

**Comment by jonathangeiger** [comment]
Okay, that's what I wanted to know. I'll fix this in a little bit. Thanks for your help!

**Comment by jonathangeiger** [comment]
I know what the essential problem with this is. It's that as_array _needs_ to be able to resolve meta-aliases but it currently cannot. I guess my point is that this is more of an architectural issue, that we want to make sure to fix in the correct way. It's a bit different from the one-off mistakes you've been reporting (which I am very grateful for, by the way!).

Paul and I are discussing the best way to resolve this. I'll keep you up to date.

**Comment by jonathangeiger** [comment]
I believe this is closed by c6b604e7e4a157c44aa39df763ea1186cb59c7ee. Thanks raeldc!

**Comment by raeldc** [comment]
Thanks Jonathan! You really rock!

**Comment by raeldc** [comment]
Uh Oh... I think something is wrong with remove(). It removes all many-to-many relationships. This is my code:

```
    $user = Jelly::select('user')->load(1);
    $admin = Jelly::select('role')->where('name', '=', 'admin')->load();
    $user->remove('roles', array($admin));
    $user->save();
```

I haven't tested `remove()` in other kinds of relationships but I'll try.

**Comment by banks** [comment]
@raeldc sounds like the same thing as #33 - follow comments there.
