### ISSUE TITLE
Many-to-many remove() removes everything 0.9.5.5

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#36]
I commented about this issue as #32. But I guess it deserves an issue on its own.

```
$user = Jelly::select('user')->load(1);
$admin = Jelly::select('role')->where('name', '=', 'admin')->load();
$user->remove('roles', array($admin));
//this doesn't work too. It deletes everything.
$user->remove('roles', 1);
$user->save();
```

You fixed #32 and #33 already, that means this isn't related to those 2.

Thanks again!

**Comment by jonathangeiger** [comment]
Just a typo here. Fixed by 3ba36f26fe0eb65e50a0df4280739650277e5eaa. Github is weird; sometimes it closes the issue but doesn't post a comment with the commit.
