### ISSUE TITLE
Feature Request: Smart unique_key()

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#37]
Would it be possible to make `unique_key` smarter? I'd like to return a different unique key depending on the `$key` in `load()`.

So I can do this:

`Jelly::select('user')->load(1);`

and

`Jelly::select('user')->load('admin');`

And return the same results. If I can override `unique_key()` like this, it would be possible. But I need to know the $key being loaded.

```
public function unique_key($value)
{
    if (is_numeric($this->_key))
    {
        return $this->_meta->primary_key();
    }
    return 'name';
}
```

Also, I'm not sure what the `$value` is in the `unique_key($value)` is for? Can you enlighten me a bit? 

Thanks!

**Comment by jonathangeiger** [comment]
This is exactly what unique_key is designed for. $value is the value that's passed to load() or some where() clause.

```
Jelly::select('user')->load('admin');

public function unique_key($value)
{
    // $value is equal to 'admin'
    if (is_numeric($value))
    {
        return $this->_meta->primary_key();
    }

    return 'name';
}
```

**Comment by raeldc** [comment]
Ok. I was just making sure because $value is always returning `NULL`. Thanks for confirming.

**Comment by jonathangeiger** [comment]
I'll check that.

**Comment by raeldc** [comment]
No need to check. It's an error on my part :).

**Comment by jonathangeiger** [comment]
No there was a bug. The $value wasn't getting passed to the alias method properly. It should work now.

c2622251eb795e754ee44145f606852ea0118af5

**Comment by raeldc** [comment]
Oh well, it was working before you fixed it. But I guess there are instances where it won't work and that's when it was getting `NULL`. 

Thanks again!

**Comment by glamorous** [comment]
Hi jonathan, I think this issue may be opened again. This isn't working for me:

```
Jelly::select('page')->with('seo')->load($uri);
```

It takes id as unique_key. I can set 'name_key', 'primary_key' and 'foreign_key' in Jelly_Meta but not 'unique_key'.

**Comment by glamorous** [comment]
After some debugging I looked where the key is set, looks like in Jelly_Core:

```
case ':unique_key':
    $field = Jelly::builder($meta->model())->unique_key($value);
```

And in the builder this code is called:

```
    /**
 * Returns the unique key for a specific value. This method is expected
 * to be overloaded in builders if the table has other unique columns.
 *
 * @param  mixed  $value
 * @return string
 */
public function unique_key($value)
{
    return $this->_meta->primary_key();
}
```

But how on earth can we do that?! :s

There is no method unique_key(), I think it's for the best to have this also in the meta to be set. If I'm wrong, I would glad to hear it. :)

**Comment by jonathangeiger** [comment]
unique_key is a method you override in your builder. You can then determine which key you want to pass back based on the value passed.
    class Model_Builder_Foo extends Jelly_Builder
    {
        public function unique_key($value)
        {
            // $value is equal to 'admin'
            if (is_numeric($value))
            {
               return $this->_meta->primary_key();
            }

```
        return $this->_meta->name_key();
    }
}
```

**Comment by glamorous** [comment]
Thanks John, it just was a bit confusing for me, because the other meta-aliases could be found in the meta-class.

Is it possible that name_key isn't unique? What I mean: if you do a where with (:unique_key) it doesn't limit the builder to 1?

Or where is it used in the code (name_key)?

**Comment by jonathangeiger** [comment]
> Thanks John, it just was a bit confusing for me, because the other meta-aliases could be found in the meta-class.

Understandable. I really don't like how that works either. Perhaps when we all move to PHP 5.3 we'll allow attaching an anonymous function to the unique_key property of your meta object, that way you don't have to override the builder class.

If you want to use the unique_key meta-alias it won't automatically limit to 1:

```
Jelly::select('foo')->where(':unique_key', '=', $value)->execute();
```

However, this always does:

```
Jelly::select('page')->with('seo')->load($uri);
```

Because load() is a shortcut for returning a single model.

> Or where is it used in the code (name_key)?

name_key isn't used anywhere within the Jelly codebase. It's just a convenience thing. Most tables I deal with have an 'id' column, and a 'name' or 'title' or some other type column that identifies the row in a human readable way. If you set name_key, you can do this:

```
echo $model->name();
```

But that's about it. You could have a uniquely identifiable name_key (like a slug or uri) and when overriding unique_key, be able to do this:

```
Jelly::select('post', 1);
```

As well as this:

```
Jelly::select('post', 'some/uri/to/the/post');
```

So your unique_key would be like this:

```
class Model_Builder_Post extends Jelly_Builder
{
    public function unique_key($value)
    {
        if (is_numeric($value))
        {
           return 'id';
        }

        return 'uri';
    }
}
```

**Comment by glamorous** [comment]
Thanks for the explanation! I'm good to go ;-)
