### ISSUE TITLE
timestamp field with auto_now_update aren't updated

### ISSUE THREAD

**Issue by SpadXIII** [jonathangeiger/kohana-jelly#38]
I'm not sure if it's my code, or if it's a bug:
    --snipp--
    ->fields(array(
        'id' => new Field_Primary,
        'created' => new Field_Timestamp(array(
            'auto_now_update' => TRUE,
        )),
    --snipp--

If I load a record, change some data and call ->save(), the timestamp field isn't updated

**Comment by banks** [comment]
Sounds like a bug! Thanks we'll take a look ASAP.

**Comment by SpadXIII** [comment]
Also, when creating an item (with $model->Jelly::factory('model'); and using $model->save()), this field and the auto_now_create timestamps aren't used/updated either.

**Comment by banks** [comment]
`auto_update_now` doesn't work because `save()` is only considering changed data (therefore the timestamp field's `save()` method is never being called as far as I can see.

Solving this will raise a couple of issues with how the architecture and coupling works. We'll look into it.

I'm not sure why the `auto_now_create` field isn't working from just looking through the code. Needs a closer look.

**Comment by banks** [comment]
I'm working on this. The create problem was a variable mis-named - none of the values changed by save() or insert IDs were getting saved back to the instance although the timestamp should of correctly updated in the database.

The update problem is a little more complex. I'll come up with the neatest solution I can for now

**Comment by banks** [comment]
Timestamp field's auto update and create features work again. Closed by fe83827dcd405ed17d77ea3246cd5cee2907e0a5 - thanks SpadXIII

**Comment by raeldc** [comment]
Hi Banks, I don't know if it's really fixed, but it doesn't work for us. :)

**Comment by banks** [comment]
> but it doesn't work for us

Are you using the master branch code? I didn't re-tag after my push.

If so, please submit a test case (or at least an example of what doesn't work for you) as I have written unittests to support this feature now working and verified them before commiting...

**Comment by raeldc** [comment]
Yes I'm using the latest.

The test is simple. I don't really know how to use unittest yet, but basic usage seems to fail.

Here's the model declaration:

```
class Model_Item extends Jelly_Model
{
public static function initialize(Jelly_Meta $meta)
{
    $meta->table('items')
        ->fields(array(
            'id' => new Field_Primary,
            'title' => new Field_String,
            'date_created' => new Field_TimeStamp(array(
                'auto_now_create' => TRUE
            )),
```

Here's the test:

```
    $item = Model::factory('item');
    $item->set(array(
        'title' => 'My Item',
    ));
    $item->save();
```

Timestamp field remains 0.

**Comment by banks** [comment]
> Timestamp field remains 0

Strange, I would expect it to be NULL. Do you have `format` set?

**Comment by raeldc** [comment]
Well, you really can't set `NULL` as default value to the `timestamp`. It defaults to `0000-00-00 00:00:00` and that means `0`.

**Comment by banks** [comment]
> Well, you really can't set NULL as default value to the timestamp

I don't quite follow you. The default value in `Field_Timestamp` is NULL so unless you have changed this and not put that bit of code in your example above, I would expect NULL to be the value you get when you do `$item->date_created`.

**Comment by banks** [comment]
Raeldc: not sure what to suggest. My unittest can be [seen here](http://github.com/jonathangeiger/jelly-tests/blob/master/tests/Jelly/Fields.php). It passes using the current master branch head. Can you have a look and verify that you aren't doing anything significantly different?

In your test case above, can you please post `Kohana::debug($item)` after you have called `save()`.

**Comment by banks** [comment]
Timestamp field's auto update and create features work again. Closed by fe83827dcd405ed17d77ea3246cd5cee2907e0a5 - thanks SpadXIII

**Comment by raeldc** [comment]
My Fault. I shouldn't have used MySQL's `timestamp` field type. Should be an `int`. I was used to using `datetime` I forgot that UNIX timestamp should just be an `int` :).

**Comment by jonathangeiger** [comment]
Note that you can use a datetime if you want, you just have to specify the format property for the field. Internally, Jelly converts all times to a UNIX timestamp but when saving them back to the database, it uses the format property if set to convert it to a format the database will understand.
