### ISSUE TITLE
Incorrect type in documentation for $field->default

### ISSUE THREAD

**Issue by leth** [jonathangeiger/kohana-jelly#39]
Hi, just a minor issue, the API for the Field class states:

public bool default
    Default value

I'm pretty sure that it shouldn't be a boolean.

**Comment by leth** [comment]
Also, how do you add a label to an issue? or is it something only Jon can do?

**Comment by banks** [comment]
I think anyone can - you select the issue in the list and then click the little arrow next to the Label and choose 'Apply to selection'. It also works while reading (although not writing) a specific issue.

**Comment by banks** [comment]
Let us know if this option is open to you or whether it is only project admins who can.

**Comment by leth** [comment]
Alas, I can't spot anything of that description.

**Comment by raeldc** [comment]
It's only project admins who can put labels :)

**Comment by glamorous** [comment]
Only admins of the project can do this :(

**Comment by banks** [comment]
Updated API docs for field. Closed by 0c3c50259c56fb4abb85843667904141090a8bf9. Thanks leth.
