### ISSUE TITLE
Plans for Field_HTML ?

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#44]
I saw it now just extend Field_text but nothing special. Is there plan for custimze it to use it for tinyMCE or some other HTML-textarea (in view) and more control for invalid input? Or is this expected for the users to add such a field in the application folder?

**Comment by raeldc** [comment]
Hmm... I would disagree including a tinyMCE or any other WYSIWYG library within an ORM Library. But I think Field_HTML would be nice with automatic xss filtering.

**Comment by glamorous** [comment]
A WYSIWYG or MarkItUp or something isn't necessary but can easily be done by the developer in the application folder (when necessary). XSS filtering and parsing valid code should be a nice feature. If nothing has to be happen by this field I suggest they delete it and allow developers to implement something like this by themself...

**Comment by jonathangeiger** [comment]
There aren't any plans to add any special processing. It's there for semantic purposes and for the fact that you can override its view to add TinyMCE or some other editor in your application if you wish.

What is "valid" HTML might be too broad of a subject to codify in that field.

**Comment by banks** [comment]
Jon, I tend to agree with glamorous. If we aren't going to provide any specific functionality of a specific view we might as well get rid of the extra classes - they are currently useless without being overridden anyway.

If you feel strongly that they should stay then I'm not too bothered wither way. Either way this issue should be closed once you've made a decision.

**Comment by jonathangeiger** [comment]
Yea. I agree. I was going to remove that and the Field_Image for now.

**Comment by jonathangeiger** [comment]
Removing Field_HTML and Field_Image for now. Closed by d533de1cb33de3a15ecd712e1f48c8cf32b8bfc7
