### ISSUE TITLE
ManyToMany relationship returns as_array

### ISSUE THREAD

**Issue by dotcreative** [jonathangeiger/kohana-jelly#45]
Refering to the discussion here:
http://forum.kohanaphp.com/comments.php?DiscussionID=4992&page=2#Comment_35775

```
object Jelly_Collection(2) {
    protected _model => NULL
    protected _result => object Database_MySQL_Result(6) {
        protected _internal_row => integer 0
        protected _query => string(128) "SELECT * FROM `brands` WHERE `brands`.`id`     IN (SELECT `products`.`brand_id` FROM `products` WHERE `products`.`category_id` = 19)"
        protected _result => resource(mysql result)
        protected _total_rows => integer 8
        protected _current_row => integer 0
        protected _as_object => bool FALSE
    }
}
```

**Comment by jonathangeiger** [comment]
Can you post the code as well as your models that gave you this result?

**Comment by dotcreative** [comment]
They are on the forum:
http://forum.kohanaphp.com/comments.php?DiscussionID=4992&page=2#Comment_35758

**Comment by banks** [comment]
OK $_model is NULL in your result which is why you get an array back rather than a model instance. We'll take a look at your code and see if we can re-create this error.

**Comment by banks** [comment]
I think it may because in your product model you have:

```
'category'    => new Field_BelongsTo(array(
                                'foreign' => 'categories.id',
                            )),
```

Note that the 'foreign' value should be `model.field` not `table.column`. If you change this to 

```
'category'    => new Field_BelongsTo(array(
                                'foreign' => 'category.id',
                            )),
```

It should work. We will make a note to make this clearer in the documentation.

**Comment by banks** [comment]
See http://jelly.jonathan-geiger.com/docs/jelly.relationships

There is a note under the examples:

> Note: Except for through in ManyToMany relationships, you should always specify a valid model. You do not need to specify a valid field in the model, however. As long as the column exists in the database, it will work.

**Comment by dotcreative** [comment]
Thanks Banks. This fixes my problem.
