### ISSUE TITLE
Support loading one-one relations eagerly with join

### ISSUE THREAD

**Issue by banks** [jonathangeiger/kohana-jelly#5]
Equivalent of ORM::with()

In this case we will have to be a little bit clever about how the database columns are aliased in the join query so we can allow for loading multiple users with different relationships for example.

**Comment by jonathangeiger** [comment]
I'll take this one.

**Comment by banks** [comment]
Cool. ORM with() is a pretty good starting point. It would be good to allow relations of relations in ORM this is done something like 

```
with('user')  // Loads the related 'user'
with('user', 'user:profile') // Loads related 'user' and their related 'profile'
```

Great work on the Docs BTW. I know a few people who are seeing the benefit of a more actively maintained library...

**Comment by banks** [comment]
This is in 0.9
