### ISSUE TITLE
Handle 'Through' tables info in ManyToMany

### ISSUE THREAD

**Issue by ccazette** [jonathangeiger/kohana-jelly#52]
This has been largely discussed in issue#42. Basically I think the 'through' table information should be accessible in the result set the same way than when a with is applied
Basic example :
If you have a user having manytomany workstations through a user_workstations table, then looping through $user->workstations as $workstation should enable you to do $workstation->user_workstation->login without generating another query.

**Comment by banks** [comment]
> do $workstation->user_workstation->login without generating another query

And what are you expecting that to "do". Return the User object? return an ID? Why do you think it is necessary to specify the through table name - surely that should be set once in the field and then just access as a relationship form then on.

I think what you are suggesting is that if you have User <= many-to-many => workstation, that you should be able to do:

```
foreach($user->workstations as $ws)
{
    $ws->user; // Doesn't do an extra query since we already know about the User

    // by extension this is now true
    if ($ws->user === $user)
}
```

This is planned as a feature but to get it to work naturally in all cases (for all relationship types) needs careful thought.

If I've misunderstood what you want, please correct me with specific examples.

**Comment by banks** [comment]
Or is 'login' a value in the through table that is unrelated to the actual user model?

I think that is what you actually mean, forget the reply above - we will think about how to allow this.

**Comment by ccazette** [comment]
Yes, I should have been clearer, sorry. Login in my example is in the through table (the login of a given user on a given workstation). 
BTW, your first answer is not related to that issue (my fault :-) but does sound amazing...

**Comment by jonathangeiger** [comment]
I agree with banks. The "no additional query" thing is something we're working on. There's nothing stopping you from setting up the through model and adding that as a field to both sides of your many to many relationship.

**Comment by banks** [comment]
> There's nothing stopping you from setting up the through model and adding that as a field to both sides of your many to many relationship.

Yep. The point of supporting many relationships through models is just this. Can you not make this work by creating a user_login model and using this rather than a plain pivot table for the many to many?

I'll close this as, as far as I am aware, this sort of relationship works and is the "correct" way to do what you are trying. If it doesn't work, please comment back and we can re-open or start a new feature request if this is still an issue that needs to be resolved.

**Comment by ccazette** [comment]
Just want to make sure there is no confusion... I am not trying to do this
`foreach($user->workstations as $ws)
{
    $ws->user; // Doesn't do an extra query since we already know about the User

```
// by extension this is now true
if ($ws->user === $user)
```

}
`
I just want to make sure the through table info is not simply lost when using manytomany. I don't really feel like this is the same, IMO the 'through' table information is a entire part of a ManyToMany relationship. While not supporting the above, ORM supports getting the through table information for instance.

**Comment by ccazette** [comment]
Oh, I see what you mean now ! Yes perhaps that could be a workaround. Let's do as you say : close it and I'll reopen it if that doesn't work.
Thanks !
