### ISSUE TITLE
Setting rules for relations (MIN and MAX amount)

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#53]
I don't know if it's intended or not. Or maybe it's already here.. But I was wondering if there is a possiblity to set rules for relationships.

For example:

A post MUST have an author
A post needs MINIMUM 1 and MAXIMUM 3 categories

**Comment by glamorous** [comment]
Or is this something for a form? So in the model you only have to say it's required, not NULL (for 1:1 relation)

**Comment by banks** [comment]
> so in the model you only have to say it's required, not NULL (for 1:1 relation)

Not sure what the problem with this is. Just add a rule to your belongsTo field saying not NULL or must be in integer greater that 0 etc.

I'm not sure there is any real benefit adding yet another way to do the same thing...

> A post needs MINIMUM 1 and MAXIMUM 3 categories

This is more complex. We'll have a think about how this should be handled. In the mean time, I would be tempted to handle this manually by creating a callback in the model instance which can check the number of related categories and return an error if necessary. It is debatable whether or not this sort of logic should be built into the core.

I guess there is an issue there of which field to attach the callback to to make it work properly. Let us know anyone if you have any ideas how this could be achieved neatly.

**Comment by glamorous** [comment]
Sorry banks, I was a little bit unclear. I knew already that it is their. I was just saying, if it's not something that a ORM has to handle, we will stick to the function we use now such as: saying it has to be an integer and not NULL.(for 1:1 relations)

I know it's something more complex. I just trow the bone, maybe it's something that more people were thinking about?

**Comment by banks** [comment]
It is definitely worth consideration - if we can find a neat way to implement something like this it would be a great feature. For now it is up to the user to find a way to make this work which may not be all that easy without some hacking.

**Comment by jonathangeiger** [comment]
I'm trying to get back up to speed with things around here, but I don't see why this shouldn't be handled by validation/callbacks. 

Is there something about the core that prevents these rules from being defined or makes them inelegant or inefficient?

**Comment by banks** [comment]
> Is there something about the core that prevents these rules from being defined or makes them inelegant or inefficient?

I guess because the related values are not directly accessible in the validation data. These can all be achieved using callbacks to the model but I think it may be worth seeing if we can define some general methods in `Jelly_Model` which provide basic validation for common relationship types that can be added as callbacks without having to define each one specifically.

**Comment by jonathangeiger** [comment]
They aren't? I've never tested it but I just assumed that they were. I'll take a look into that.

**Comment by banks** [comment]
I could be wrong there. This whole thing needs a little investigation.

**Comment by jonathangeiger** [comment]
I just tested it. All fields can be validated. Just to lay down how it all works here:
- When inserting, all data is validated. When updating, only changed data is validated.
- For relationships, a primary key or an array of primary keys (depending on the relationship type) is what will be passed to the validation methods. 

Thus, it's possible to create a min or max validation rule and use that.

**Comment by glamorous** [comment]
Thanks jonathan, can you provide an example of this in the docs or add this to the "todo" for the documentation... This is something that isn't obvious for the users so an example should be a great help!
