### ISSUE TITLE
Field_File error

### ISSUE THREAD

**Issue by ginad** [jonathangeiger/kohana-jelly#56]
Unable to upload and validate file, maybe because Jelly_Field_Core converts the $_FILE array to string.

**Comment by banks** [comment]
We haven't tested this functionality thoroughly yet. Thans for the tip - we'll take a look when we can.

**Comment by ivanhobor** [comment]
in /class/jelly/field/file.php

add

```
public function set($value)
{
    return (array)$value;
}
```

**Comment by jonathangeiger** [comment]
Fixing file uploads. Closed by 6bc83d208e6755cd13e45600ff732bf1b6c0603e. I'm a bit leary about this commit because I can't see a way to unit test file uploads.
