### ISSUE TITLE
$model->label() just like $model->input()

### ISSUE THREAD

**Issue by SpadXIII** [jonathangeiger/kohana-jelly#57]
This probably relates to the discussion on the kohana-forums about the input-/form-integration of Jelly, but in the mean time it would be nice to be able to access the $model's field labels just like it's possible with the inputs.

Overruling the current input templates is possible ($label is available within the template) but not really desirable. It might be easier to just use `$model->label('field')` to retrieve the label-text and/or a <label> (using `Form::label()`).

**Comment by banks** [comment]
What is wrong with `$model->meta()->fields('field')->label`?

We are almost certainly going to be removing inputs soon anyway so I'm not sure it is worth putting even more support for this sort of thing in.

**Comment by SpadXIII** [comment]
Ah, I hadn't figured that route out just yet. Thx for the heads-up!

**Comment by SpadXIII** [comment]
Using `$model->label('field')` would only save a few characters for typing.

Double comment: forgot to close this non-issue
