### ISSUE TITLE
count() desn't work with $meta->load_with()

### ISSUE THREAD

**Issue by dotcreative** [jonathangeiger/kohana-jelly#58]
In Jelly_Core when you run execute() checks for sorting() and load_with() from $meta, but count() doesn't. As a result when you run count on query that has load_with() and use a where that depends on a foreign field it generates an error.

**Comment by banks** [comment]
Thanks for the report.

**Comment by banks** [comment]
Closed by 34c1cc9246ec3837d183908d0db53bcf381bf13f. Thanks dotcreative.

Also introduces a slight functional change: not model's default sorting is only added to select query when order_by() hasn't been explicitly called allowing it to be overriden.
