### ISSUE TITLE
Support serialising Jelly models with loaded relations

### ISSUE THREAD

**Issue by banks** [jonathangeiger/kohana-jelly#6]
One issue I have had with Sprig which will be the same in Jelly is that models can't be serialized once n:many relations have been loaded since the related objects are stored in a Database_Result object which (in case of MySQL) depends on a result resource.

My solution in Sprig was to implement the magic __sleep method which looped through all related models stored and converted any Database_Result objects into Database_Result_Cached objects. The result then serialised fine.

This is most significant because of the way kohana's auth module works - it serialises the user and then expects to be able to retrieve the user, and their related roles, from the session.

I'm happy to put this in at some point - it is pretty simple.

**Comment by banks** [comment]
See http://github.com/shadowhand/sprig/issues#issue/40 for Sprig solution.

**Comment by raeldc** [comment]
Oh so this is what you were talking about in the forum. So I guess no one will be able to write a Jelly Driver for Auth without this feature. Banks, how easy/hard is it to write a driver for Auth? You created Sprig-Auth, so you have an idea. If it's pretty simple, maybe you can do it quickly? :)

**Comment by banks** [comment]
Not hard - my sprig driver will be very close to the right code for jelly. I don't have a lot of time right now so if you need this soon have a go yourself. If noone has done it by the time I get some other things done I'll write it. 

An auth driver can work before we fix this in the same way my sprig one does but hopefully well fix this in jelly in the next few days anyway. You can et all the hard bits of auth working without this...

**Comment by jonathangeiger** [comment]
Closed by 5d6e72e57337b370d91b9c5bd4220126cf16065f

**Comment by jonathangeiger** [comment]
Sorry about all the other crap in that commit. My mistake.
