### ISSUE TITLE
Field Validation Rules Overwritten by Custom Rules

### ISSUE THREAD

**Issue by Fenstar** [jonathangeiger/kohana-jelly#60]
Validation rules supplied to Field classes on instantiation overwrite the original rules set by said classes.

Perhaps the expected behaviour would be to append the new rules, avoiding needless repetition.  Issue first raised at: http://bit.ly/99eqUj

**Comment by jonathangeiger** [comment]
Wouldn't it then make it impossible to remove rules that were already defined if they were merged?

**Comment by Fenstar** [comment]
Unless a means for overwriting were present, then yes it would.  I'm not convinced this is much of an issue, as it only applies to the email field as far as I'm aware, and that only defines one rule.  I thought I'd follow up the suggestion to report it anyway, in case fields one day appear with more complex rules...

**Comment by jonathangeiger** [comment]
I think for now this is a non-issue, so I'm going to close it. Even if we did have complex rules that could be overwritten, simply appending wouldn't be a proper solution.
