### ISSUE TITLE
Suggestion for Field labels

### ISSUE THREAD

**Issue by ginad** [jonathangeiger/kohana-jelly#63]
I suggest using Form::label in displaying the label for an input, because right now it just returns a string.
    if ( ! $this->label)
        {
            $this->label = inflector::humanize($column);
        }
                $this->label = Form::label("field-{$column}",$this->label);

**Comment by banks** [comment]
It's up to you which HTML tags you want to put around the label. We are planning to remove all HTML from Jelly so this probably will never happen.

See the forum post about form genration and jelly to get a better idea of our reasoning.
