### ISSUE TITLE
Double $field->set($value) in Jelly_Model_Core::set()

### ISSUE THREAD

**Issue by homm** [jonathangeiger/kohana-jelly#64]
Is it correct, what $field->set($value) call twice in Jelly_Model_Core::set()?

http://github.com/jonathangeiger/kohana-jelly/blob/master/classes/jelly/model/core.php#L300
http://github.com/jonathangeiger/kohana-jelly/blob/master/classes/jelly/model/core.php#L312

**Comment by banks** [comment]
No, that looks like a bug. Thanks. Jon's recent branch work may have changed this though so I'll let him resolve it as is best.

**Comment by jonathangeiger** [comment]
Closed by 5b3ee9e5e553926a28b9b240e3d62ad9c4beea37
