### ISSUE TITLE
All main files named core.php

### ISSUE THREAD

**Issue by homm** [jonathangeiger/kohana-jelly#66]
This is very inconvenient when search file in IDE tabs.

I think hierarchy in file system might be something like this:

<pre>
classes\
--field\
----float.php
----file.php
--jelly\
----field\
------float.php
------file.php
----jelly\
------builder.php
------collection.php
------field.php
------meta.php
------model.php
----builder.php
----collection.php
----core.php
----field.php
----meta.php
----model.php
--jelly.php
</pre>

**Comment by banks** [comment]
So the classes would be called `Jelly_Jelly_Builder` etc.? That seems like an even less satisfactory solution to me.

I have no problem in my IDE but I agree that it is not ideal to have everything called core.php. We will consider if there is an alternative naming scheme that makes sense. Perhaps `Jelly_Builder extends Jelly_Core_Builder` would be better.

**Comment by homm** [comment]
Another suggestion — call like in Kohana and standard ORM/

<code>Jelly_Builder extends Kohana_Jelly_Builder</code>

**Comment by ccazette** [comment]
Either of the last 2 solutions seem indeed better than the current naming.

**Comment by banks** [comment]
> call like in Kohana and standard ORM

This is not an official module and the Kohana name is reserved for that purpose.

**Comment by jonathangeiger** [comment]
I thought quite a bit about naming them this way and ultimately decided against it. In textmate, I do a ⌘+T and type in "core" to see all of the core files. I can then use my arrow keys to decide which one I want.

If we do something like:

```
Jelly_Builder extends Kohana_Jelly_Builder
```

I type in "builder" and have to visually inspect which folder I want, which is much more difficult, in my opinion.

**Comment by banks** [comment]
It makes little difference to me either way. Although we definitely can't and shouldn't use the prefix Kohana as that will confuse people about whether it is an official module. I don't mind the `Jelly_Core_Builder` strategy but I'm not too bothered to be honest. I guess the question is easier to open using text entry shortcut, or easier to tell which is which once they are all open as tabs? Even then there could be confusion between the actual classes and the core versions. I'd say we stick.

**Comment by jonathangeiger** [comment]
Okay. Closed.
