### ISSUE TITLE
Error while call input() for timestamp on exists object

### ISSUE THREAD

**Issue by homm** [jonathangeiger/kohana-jelly#68]
I get error "A non well formed numeric value encountered" when try code:

$model = Jelly::select('model_name', 1);
$model->input('timestamp_field');

http://i44.tinypic.com/59x11y.png

**Comment by jonathangeiger** [comment]
The error suggests it's a problem with the value being passed to date(). Can you let us know what value that is?

**Comment by homm** [comment]
Date arguments shown on attached image. It is 'r' and '0000-00-00 00:00:00'
Or I misunderstand you question?

(I'm sorry I accidentally close ticket.)

**Comment by jonathangeiger** [comment]
0000-00-00 00:00:00 shouldn't be passed to date(), which expects a UNIX timestamp. I wanted to know what the UNIX timestamp was, to ensure the field is converting it properly.
