### ISSUE TITLE
CodingStyle

### ISSUE THREAD

**Issue by dewos** [jonathangeiger/kohana-jelly#7]
This's marginal, but would be nice if the core could follow more the official kohana styling conventions for comparison and parentheses.

http://dev.kohanaphp.com/wiki/kohana2/CodingStyle

if(!$foo)   become   if( ! $foo)
if (($foo && $bar) || ($b && $c))  usually become  if (($foo AND $bar) OR ($b AND $c))

**Comment by glamorous** [comment]
Is there a reason why some properties are placed between some methods?

**Comment by jonathangeiger** [comment]
Everyone asks about this and I don't really get why. The _entire_ Kohana 3.0 source is structured this way:
1. static properties
2. static methods
3. instance properties
4. instance methods

**Comment by glamorous** [comment]
That makes sense... :)

**Comment by dewos** [comment]


**Comment by dewos** [comment]
I am closing this since it's fixed now.

**Comment by jonathangeiger** [comment]
Thanks. I was going to keep it open until I merged the unstable branch to master, but if you're happy now then I am too. :)
