### ISSUE TITLE
Let's discuss about populate()

### ISSUE THREAD

**Issue by homm** [jonathangeiger/kohana-jelly#70]
I believe what necessary additional method populate() for fields and model. This method must receive data from forms according format, generated by input().

For many cases it will be same as set() function, but in more complex cases it will be different.

Some examples:
Datetime fields with separated inputs for month, day and year.
File upload field may get upload in populate() and anything else (depend of application) in set().
ManyToMany fields may build it's own inline forms (like in Django) for related objects.
And many others…

**Comment by banks** [comment]
We are planning to remove all form functionality from the core ORM and encourage separate Form helper module for this sort of logic so this is not likely to happen. You can read mre or join the discussion [in this thread](http://forum.kohanaphp.com/comments.php?DiscussionID=5068&page=2#Item_2).
