### ISSUE TITLE
Field->_input_view() go in infinite recursion

### ISSUE THREAD

**Issue by homm** [jonathangeiger/kohana-jelly#72]
If Kohana::find_file('views', $view) return FALSE, this method go to infinite because.

Now:
    // Check we can find a view for this field type, if not inherit view from parent
    if ( ! Kohana::find_file('views', $view) 
        // Don't try going beyond this base Jelly_Field class!
        AND get_parent_class($this) !== **CLASS**)

Should be:
    // Check we can find a view for this field type, if not inherit view from parent
    if ( ! Kohana::find_file('views', $view) 
        // Don't try going beyond this base Jelly_Field class!
        AND get_parent_class($field_class) !== **CLASS**)

**Comment by jonathangeiger** [comment]
Closed by 20663f45fed435f7534f86d1aa0d3e9978db7d69. Thanks homm!
