### ISSUE TITLE
Error in jelly.cud docs

### ISSUE THREAD

**Issue by dewos** [jonathangeiger/kohana-jelly#73]
Model::factory instead of Jelly::factory.

**Comment by dewos** [comment]
mmmm, maybe i made a mistake

**Comment by banks** [comment]
Nope quite right, thanks. Fixed by 1c2c58be39035364cd5d2a795c54f00837fb0ce9

**Comment by dewos** [comment]
See http://github.com/jonathangeiger/kohana-jelly/blob/master/classes/jelly/core.php#L47 too

**Comment by banks** [comment]
Thanks Dewos, Jon uses the `Model` alias in some of his apps so he sometimes forgets and writes it instead of `Jelly` in examples!
