### ISSUE TITLE
Cant set values when Overloading __contsruct in Jelly_Builder

### ISSUE THREAD

**Issue by mintbridge** [jonathangeiger/kohana-jelly#77]
I'm overloading the __construct() in Jelly_builder to do a few things in a model but when i try and set a value, although it gets into the _changed arry() it always gets set to NULL, is this expected?

Example:

<pre>
<?php
class Model_Builder_Event extends Jelly_Builder
{
    public function __construct($model = NULL, $type = NULL)
    {
        if($type === Database::INSERT)
        {
            $model->account = 1;
        }
        parent::__construct($model, $type);
    }
}
?>
</pre>

i also tried using $this->set() and it also didnt work

<pre>
<?php
class Model_Builder_Event extends Jelly_Builder
{
    public function __construct($model = NULL, $type = NULL)
    {
        if($type === Database::INSERT)
        {
            $this->set(array('account'=>1));
        }
        parent::__construct($model, $type);
    }
}
?>
</pre>

Any thoughts?

Paul

**Comment by banks** [comment]
I'm a little confused. Do you really want to do this in builder? Builder just lets you modify the qay queries are built. It has nothing to do with actual model instances itself.

What are you trying to do here? It looks like Builder is not the right place for it!

If you want all new instances to have a value of 1 for account then set that as the default value for the field. Or define `__construct()` in the MODEL class and set the value on every new instance (after all other construction has happened).
