### ISSUE TITLE
Field_Password 'hash_with' is called every time the model is loaded.

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#8]
Hey Jonathan, I'm almost done developing the Jelly Auth Driver. Problem is, Jelly seems to suffer the same fatal flaw with Sprig. It hashes values every time a model is saved and loaded.

It's not a problem on saving, but it's a big problem if it hashes an already hashed password from the database. I would have applied the solution from Issue 61 of Sprig but since Jelly's architecture is different, I don't know how to fix this without delving deep into Jelly Core.

**Comment by jonathangeiger** [comment]
I've already fixed this with 51246b71f5ed39fa917e159a1c0ff51daf4015ab. Why don't you pull the latest updates and let me know that I fixed your problem. I've also added unit tests for it here: 

http://github.com/jonathangeiger/jelly-tests/commit/2e9660cca6688b82947bccff4c5ae9b52dacdb4a

BTW, I also added support for non-editable fields here: 6ecca81decb155f3828164ac6c764182e9dd237d

**Comment by raeldc** [comment]
Oh Sorry I didn't update. I'll be testing it and I'll give you a feedback. Thanks!

**Comment by jonathangeiger** [comment]
Closing this for now. If it's still broken, re-open it.
