### ISSUE TITLE
Just asking for an explanation...

### ISSUE THREAD

**Issue by ccazette** [jonathangeiger/kohana-jelly#83]
Could someone explain me something please ?
I don't quite get the interest of having a Jelly_Meta class where you statically put all structural aspects of your models if you then have a "meta" property for each instance of the model, with the whole Meta object... I would say (not sure really, may be it is only a reference, I am not really confident about how PHP works in that area) it is really memory consuming and makes really big objects to deal with, whereas I thought one the big advantages of having a Meta out of the Model was to reduce the footprint of the model by getting rid of structural info and focusing on instance data.

Can someone shed some light on this please ?

**Comment by jonathangeiger** [comment]
It's a reference so you only instantiate one meta object per model class. Even if you have 100 instances of a model, your fields, meta object, etc are only instantiated once. 

In PHP5 all objects are passed around as references.

**Comment by ccazette** [comment]
I was not sure about this. Will read more. Thank you !
