### ISSUE TITLE
File field still returning the entire path instead of the filename only

### ISSUE THREAD

**Issue by ginad** [jonathangeiger/kohana-jelly#85]
just a minor correction :)

if (is_string($value))
{
  $value = trim($filename, DIRECTORY_SEPARATOR);
}

it should be 

if (is_string($value))
{
  $value = trim($value, DIRECTORY_SEPARATOR);
}

Thanks guys you're doing great :)

**Comment by jonathangeiger** [comment]
Closed by a3b0e6c8d75d146105795de5ddcfd20c2e67636b. Thanks ginad!
