### ISSUE TITLE
Bug: Object of class Model_Foo could not be converted to string

### ISSUE THREAD

**Issue by Lokaltog** [jonathangeiger/kohana-jelly#88]
I have a many-to-many relationship that triggers this error whenever I try to add a relation:

```
$bar = Jelly::factory('bar')->save();
$baz = Jelly::select('baz')->with('foo')->load($id);
$baz->add($bar)->save(); // Model_Foo could not be converted to string
```

I have to use `with('foo')` or the query will fail (Jelly tries to run a subquery that returns all the columns in 'foo' which also seems like a bug because a `bar_id = (select ... from foo)` subquery can't return more than one column).

If I use `with()` to load the related model, I get the error message above. I think this may be solved by implementing a `__toString()` method in `Jelly_Model_Core` that returns the primary key of the model. I added this function to `Jelly_Model_Core`, and now everything works fine:

```
public function __toString()
{
    return (string) $this->get($this->_meta->primary_key());
}
```

**Comment by Lokaltog** [comment]
BTW, the official Kohana ORM has an almost identical method:

```
public function __toString()
{
    return (string) $this->pk();
}
```

**Comment by glamorous** [comment]
If you want to echo a Model I would expect that he would return the "name_key"... __toString() should always been used to show what the model is.. By returning an ID, that isn't the thing I suppose.

**Comment by jonathangeiger** [comment]
Can you post your model declarations and working code?

**Comment by Lokaltog** [comment]
As this is a closed project, I can't post any raw source code here. Is it okay if I PM you the model declarations and code? Do you need the database structure for the related tables as well? (I'm using PostgreSQL via PDO)

**Comment by jonathangeiger** [comment]
That's fine. I just need enough to understand what's going on, so your models and code should be enough.

**Comment by jonathangeiger** [comment]
Lokaltog sent me his files and it had to do with him trying to set a belongs_to field as a primary key. Just for the record here, primary keys can only be primitive types, basically strings or integers.

That said, if you wanted to have a belongs_to and a primitive type reference the same column, you can do something like this:

```
class Model_Foo extends Jelly_Model 
{
    public static function initialize(Jelly_Meta $meta) 
    {
        $meta
            ->primary_key('user_id')
            ->fields(array(
                'user_id' => new Field_Integer,
                'user' => new Field_BelongsTo,
                // ...
            ));
    }
}
```
