### ISSUE TITLE
Please suggest solutions for Jelly Auth

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#9]
Look at my [Jelly User Model here](http://github.com/raeldc/jelly-auth/blob/master/classes/model/auth/user.php).

I have 2 issues that when solved, will make Jelly-Auth Driver fully functional.
#1. Rules expect arrays. If you look at the rules declaration for min_length, max_length, etc, they are just simple integers. But the Validate class expects those values to be arrays. I can make them arrays, but it doesn't seem neat. What I did temporarily was to hack line 1013 of Jelly_Core_Model and make sure that an array is passed to $data->rules.
#2. Callback for password_matches. Sprig-Auth simply does this:

```
'callbacks' => array(
'matches' => array($this, '_check_password_matches')
),
```

But since the architecture of Jelly is different, $this is not recognized. What is the best way to do this in Jelly?

Thanks!

**Comment by banks** [comment]
> I can make them arrays, but it doesn't seem neat

It is how the validate class is designed to be used I don't think we should encourage non-standards - it will only confuse people. Your best bet is to see if the Kohana devs are happy to support this in validate. Actually it should work anyway since they cast $params into an array in Validate::rule() but you will get an exception because of the type hint in the function declaration. I feel there is a string case for Validate to be changed but I'm reluctant to add hacks to Jelly for this.

Regarding point 2. I guess the answer is to make it a static method. There is no real need for it to be an instance method since it doesn't acces any properties of $this

So:

```
'callbacks' => array(
    'matches' => array('Model_Auth_User', 'check_password_matches')
),
```

**Comment by raeldc** [comment]
There is no need to hack or override the Validate class. It's just that you can do something about it in Jelly, some kind of a shortcut. Something like this on Jelly_Core_Model line 1013

```
if ($field->rules)
        {
            $rules = array();
            foreach ($field->rules as $key => $rule) 
            {
                if ( ! is_array($rule)) 
                {
                    $rules[$key] = array($rule);
                }
            }
            $data->rules($column, $rules);
        }
```

**Comment by raeldc** [comment]
To make my point clear, here's a code that adheres to the Validate Class.

```
public static function initialize(Jelly_Meta $meta)
{
    $meta->primary_key = 'name';
    $meta->fields += array(
        'id' => new Field_Primary,
        'name' => new Field_String(array(
            'unique' => TRUE,
            'rules' => array(
                'max_length' => array(32),
                'not_empty' => array(TRUE)
            )
        )),
        'description' => new Field_Text,
        'users' => new Field_ManyToMany
    );
}
```

Notice that maxlength and not_empty had to be an array, if not, PHP will throw an exception. Those values can simply be an integer or a boolean.

**Comment by banks** [comment]
I know what you are saying.

In my mind that array syntax is a standard defined by Validate class. If we mess around with types just to save typing 7 characters a couple of times in code you should never need to change I think that is wasted effort. I also think it will be more confusing for people who use jelly and then can't use the same syntax to validate data outside of Jelly.

If it is really a big deal, get kohana devs to change Validate but I don't feel we should introduce this into Jelly core.

Ultimately it is Jon's decision. I just don't think it is worth it.

**Comment by jonathangeiger** [comment]
I agree with banks. This is something that you should take up with the Kohana maintainers.
