### ISSUE TITLE
Select functions in Jelly_Builder

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#90]
Having some troubles with the 'FUNC' functions in the query-builder. When I use this:

```
Jelly::select('event')->select('YEAR(FROM_UNIXTIME("startdate"))')->past()->open();
```

Then my query is:

```
SELECT YEAR(FROM_UNIXTIME(`rcc_events`.`startdate`)) FROM `rcc_events` WHERE `rcc_events`.`enddate` < 1269990282 AND `rcc_events`.`status` = 'open' ORDER BY `rcc_events`.`startdate` ASC
```

But better should been to define an 'AS xxxx'. In #40 this came along...

I already tried what banks suggested:

```
echo Jelly::select('event')->select(array('YEAR(FROM_UNIXTIME("startdate"))' => 'jaar'))->past()->open();
```

But that throws an error:

ErrorException [ Notice ]: Undefined offset: 0
MODPATH/jelly/classes/jelly/builder/core.php [ 247 ]

```
foreach ($columns as $i => $column)
{
    if (is_array($column))
    {
        $columns[$i][0] = $this->_column($column[0], TRUE);    //THIS LINE BREAKS
    }
    else
    ...
```

Maybe I don't use the correct syntax but this is not quiet good documented so I don't know better... :-)

If I would have some more time, I would definetly look into it and try to fix it myself but it's getting late and my time is running down :(

My goal for this query is to recieve all years from al my events, so a distinct should be a good addition for my query, is this possible?

Thanks and sorry for all the issues! :) Just trying to complete my project and help debugging Jelly :-D

**Comment by banks** [comment]
Sorry if I posted that, the correct syntax for aliasing columns in kohana query builder would be this:

```
select(array('YEAR(FROM_UNIXTIME("startdate"))', 'jaar'))
```

Note values are elements 0 and 1 and not key => value. This is to get around the limitations PHP places on array keys. For example if you wanted to alias a subquery, you would need the first part to be a query object and PHP can't use objects as array keys.

**Comment by glamorous** [comment]
So that would be possible to, to have a subquery in that array?

What about the DISTINCT function?

(btw thanks for the update)

**Comment by glamorous** [comment]
Already found it, sorry for your time ;-)

http://jelly.jonathan-geiger.com/docs/api/Jelly_Builder_Core#distinct
