### ISSUE TITLE
ManyToMany Trough as a Model, howto?!

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#91]
This is my setup:

```
class Model_Event extends Jelly_Model
{
    public static function initialize(Jelly_Meta $meta)
    {
        $meta->fields(array(
            'id' => new Field_Primary,
            'uri' => new Field_Slug,
            // some more...
            'rsvps' => new Field_ManyToMany(array(
                'foreign' => 'user',
                'through' => 'rsvp',
            )),
        ))
            ->sorting(array('startdate' => 'ASC'));
    }
}
```

And I have a model Rsvp:

```
class Model_Rsvp extends Jelly_Model
{
    public static function initialize(Jelly_Meta $meta)
    {
        $meta->table('rsvps')->fields(array(
            'user' => new Field_BelongsTo,
            'event' => new Field_BelongsTo,
            'rsvp' => new Field_Enum(array(
                'choices' => array('yes','no','maybe'),
            )),
        )),
    }
}
```

I think this is correct, if not, correct me please.

Then in my view where $item is a Model_Event:

```
echo Kohana::debug($item->rsvps);
```

Then I get a Jelly_Collection with Model_user objects in it. I thougth I would receive Model_Rsvp object?

Can someboy with some more experience with Jelly say if this is the correct way to do or not?!

**Comment by coreyworrell** [comment]
Looks like Event should be HasMany not ManyToMany

**Comment by SpadXIII** [comment]
@glamorous: The return of a Jelly_Collection is correct. I also think you should be using HasMany, like coreyworrell said. One Event HasMany Rvsp, One Rvsp BelongsTo One Event .. ManyToMany relations are a bit different, and need a table in the middle to connect 2 primary keys.

You can loop the Jelly_Collection in a foreach and you'll get a Model_Rvsp inside the loop.

**Comment by glamorous** [comment]
Well, Rsvp is the column in the middle between events and users...

I have events that has many users, and many users have many events...

RSVP is the column in the middle but I want to use a model for it so I can have extra columns like their respond to the event...

If I'm wrong with my relations, I would like to hear for what use the trough model can be used then?

edit: I'm aware of getting a Jelly_Collection but except Model_Rsvp's in it instead of Model_Users, so I can do something like this:

```
foreach($event->rsvps as $rsvp)
{
    $rsvp->user->name;
}
```

**Comment by SpadXIII** [comment]
A ManyToMany relation with a model in the middle (instead of table) is something I haven't done yet. I'm also not sure if it's possible the way you have done it now. Or at least, the results you're expecting aren't possible.

I'm just guessing here: ManyToMany with a model in between is different:
Event -HasMany-> <-BelongsTo- Rvsp -BelongsTo-> <-HasMany- User

**Comment by banks** [comment]
> edit: I'm aware of getting a Jelly_Collection but except Model_Rsvp's in it instead of Model_Users, so I can do something like this:

Then through isnt right. You are creating a relationship between Events and Users so of course you will get user models back! If you actually want rsvp models, then you should create the realtions as SpadXIII has suggested. The only point I can see of through relations is where you want to have the relationship as a separate model but you don't want to have to load the 'pivot' model every time you access the relationship.

For example, you may want an rsvp model for getting comments and dates etc but you actually just want a list of who is attending an event without loading all their notes and dates, in this case you could use something like:

```
class Model_Event extends Jelly_Model
{
    public static function initialize(Jelly_Meta $meta)
    {
        $meta->fields(array(
            'id' => new Field_Primary,
            'uri' => new Field_Slug,
            // some more...
            'users' => new Field_ManyToMany(array(
                'foreign' => 'user',
                'through' => 'rsvp',
            )),
        ))
            ->sorting(array('startdate' => 'ASC'));
    }
}
```

Then you could do

```
$attending = $event->users->where('rsvp', 'yes')->execute(); // Gets a list of all users directly without loading rsvp models
```

In this situation you would still need a separate HasMany relationship with RSVP model if you want to directly retrieve the user's other RSVP info like date accepted and comment etc.

Make sense?

**Comment by SpadXIII** [comment]
That's indeed a clever solution. It's basically a ManyToMany relation, only the through-table is also a model. The relations to the through-model should be defined separately indeed.

**Comment by glamorous** [comment]
@banks, that makes sense! Didn't knew that I can perform a "where" here:

```
 $attending = $event->users->where('rsvp','yes')->execute();
```

Ok, I will use then this for get the results for every choice! :)

Thanks for the help! :)

If you want I can write some extra tutorials with live code after finishing my project for some basic usage that isn't covered with the documentation...

**Comment by banks** [comment]
> Didn't knew that I can perform a "where" here

Actually you can't I was wrong. But you can if you do it like this:

```
$attending = $event->get('users')->where('rsvp', '=', 'yes')->execute();
```

**Comment by banks** [comment]
Bear in mind that using `get()` just returns the query builder with the realtionship parts set but unexecuted so you can do whatever you like. This also means though that the result is not cached internally:

```
$users = $event->users;
$users_again = $event->users; // No query here since we cached the full set of related users internally
```

BUT:

```
$users = $event->get('users'); // no query here as get() returns builder
$users = $users->execute(); // loads users
$users_again = $event->users; // Another query is done here since the first query was outside the model and therefore not cached.
```

**Comment by glamorous** [comment]
Thanks! :) All those possibilities, lot to learn... ;-)
