### ISSUE TITLE
Meta_Core db group

### ISSUE THREAD

**Issue by kippel** [jonathangeiger/kohana-jelly#96]
The code now is:

   /**
         \* Gets or sets the db group
         \* @param   string  $value
         \* @return  string|$this
         */
        public function db($value = NULL)
        {
                if (func_num_args() !== 0)
                {
                        return $this->set('db', $db);
                }

```
            return $this->db;
    }
```

I think should be:

   /**
         \* Gets or sets the db group
         \* @param   string  $value
         \* @return  string|$this
         */
        public function db($value = NULL)
        {
                if (func_num_args() !== 0)
                {
                        return $this->set('db', $value);
                }

```
            return $this->db;
    }
```

to set correctly the db property

**Comment by jonathangeiger** [comment]
Closed by 0a9bcf2da47b7168aa94b964c82272700728fd1e. Thanks kippel!
