### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kaltar** [jonathangeiger/kohana-jelly#98]
I've never used github, so I'll submit this as an issue.
classes/jelly/meta/core.php
Line 235

```
public function db($value = NULL)
{
    if (func_num_args() !== 0)
    {
        return $this->set('db', $db);
    }

    return $this->db;
}
```

Shouldn't line 239 be

return $this->set('db', $value);

All calls are being done with a null value, that's why it hasn't been found yet.

**Comment by banks** [comment]
You're right but this is already reported in #96. Thanks for posting. Please use more precise titles in the future though - it's very hard to keep track of issues if they are just called 'question'!

**Comment by kaltar** [comment]
Oops... Sorry! I'll try to submit the code next time Mr Banks :)
